### ISSUE TITLE
Proposal: CentOS builds on 32-bit Arm

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/equinix-metal-arm64-cluster#144]
Starting out a conversation about CentOS builds for 32-bit Arm systems.

### Name, email, company, job title

Ed Vielmetti, Packet
@arrfab

### Project Title and description

CentOS builds on 32-bit Arm. Provide 32-bit infrastructure to speed up armhf builds for CentOS.

### Which members of the community would benefit from your work?

Anyone using CentOS on 32-bit Arm systems; the CentOS ecosystem in general.

### Is the code that you’re going to run 100% open source? 

Provide the URLs where it is located, or a Git repository.

[TBD]

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

One 32-bit capable system as a start, either Ampere or Hisilicon.

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

[TBD]

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

[TBD]

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

[TBD]

**Comment by arrfab** [comment]
Let me complete the "TBD" fields for the request : 

## Is the code that you’re going to run 100% open source?
## Provide the URLs where it is located, or a Git repository.

All code that would be built and eventually tested on such nodes would be hosted on https://git.centos.org

## What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

One 32-bit capable system as a start, either Ampere or Hisilicon.
Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

our CI dashboard is available at https://ci.centos.org but for host *behind* that jenkins node (and so hosted internally). We can find a way to trigger remote jobs/results on that jenkins node if needed

## Describe the monitoring system in use or desired for this project.

## Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

We use Zabbix as monitoring solutions, but so far we don't publish the resources utilization, especially for nodes in our infra

## Please state your contributions to the open source community and any other relevant initiatives
CentOS is a well-known distribution, rebuilding the upstream sources used for RHEL, and also covering other architectures not existing in RHEL (like armhfp on our side, built/patched from upstream sources)

**Comment by arrfab** [comment]
just got notification that it will be closed .. does that mean that the initial proposal wasn't accepted ? (just curious)

**Comment by vielmetti** [comment]
It's approved - just setting up now. (the stale bot keeps me honest)

**Comment by vielmetti** [comment]
Approved - and I have added a Hisilicon server to the project.

**Comment by pgmwoa** [comment]
@arrfab, Waiting for your response on the server upgrade. Please

**Comment by arrfab** [comment]
@pgmwoa : sorry for the late answered but replied and previous server returned to Equinix/WoA

**Comment by pgmwoa** [comment]
> @pgmwoa : sorry for the late answered but replied and previous server returned to Equinix/WoA

Thanks a lot for freeing the old server. Please let us know in case of any issues with new server. We would need some more details related to usage, as requested in the email.

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same.
