### ISSUE TITLE
Proposal: SIG-Kind

### ISSUE THREAD

**Issue by hh** [WorksOnArm/equinix-metal-arm64-cluster#154]
If you are just making a comment, ignore/delete those fields and file youe.

### Name, email, company, job title

Hippie Hacker, hh@ii.coop, CNCF
Benjamin Elder, bentheender@google.com, Google
James Munnelly, JetStack

### Project Title and descriptiBen the Elder on

Kind is Kubernetes in Docker and available at sigs.k8s.io/kind

### Which members of the community would benefit from your work?

Anyone needing to spin up and tear down k8s clusters for CI usage on ARM.

### Is the code that you’re going to run 100% open source? 

https://github.com/kubernetes-sigs/kind

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

A couple Ampere reservations, seems we are out of the old ones.
One will be long term, the second will be for trying out alternation configurations, likely not running all the time.

### Describe the continuous integration (CI) system in use or desired for this project.

Ideally we'll be using prow to test commit's on an ARM cluster / docker daemon running on this infra.

https://k8s-testgrid.appspot.com/sig-testing-kind

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

### Please state your contributions to the open source community and any other relevant initiatives

@bentheelder and the @munnerz are long standing contributors to k8s.
@hh works with the CNCF on various infrastructure projects benefiting our community.

**Comment by jacobsmith928** [comment]
+1, possibly fulfill with Qualcomm Centriq systems for the time being?

**Comment by spiffxp** [comment]
FWIW SIG Kind isn't really a thing, kind is technically a subproject of Kubernetes SIG Testing (ref: https://github.com/kubernetes/community/tree/master/sig-testing#subprojects).  But yes wholeheartedly behind this request as one of SIG Testing's chairs

**Comment by vielmetti** [comment]
Two Qualcomm servers now available in this project - @hh let me know when you have them up and going.

**Comment by vielmetti** [comment]
Reopening this issue, as our Qualcomm gear is very orphaned and is going away.

@hh - if this is still a need for it, let's arrange plans to migrate the arm64 support from this old server to a newer one; and if the project to do the port has completed its work, let's look for an efficient way for them to keep the work running. 

@pgmwoa -  this machine had originally been part of the Works on Arm contribution to the CNCF CIL - we can adjust the sponsorship, but you should know that the system had been largely untracked and just came up in a CNCF audit.

**Comment by BenTheElder** [comment]
IIRC we shut this down, I'm not sure what it had before but I don't think @aojea or I need this currently. Thank you!

**Comment by vielmetti** [comment]
Closing this issue as completed; if there is a renewed need for Kubernetes SIG Testing to engage, there's open channels to do so.
