### ISSUE TITLE
kubevirt/kubevirt CI

### ISSUE THREAD

**Issue by zhlhahaha** [WorksOnArm/equinix-metal-arm64-cluster#203]
Kind attention: @kalyxin02 @lubinsz @cayu53
Name, email, company, job title
Howard Zhang, howard.zhang@arm.com, Arm, software engineer

**Project Title and description**
KubeVirt (https://github.com/kubevirt/kubevirt) is a virtual machine management add-on for Kubernetes. The aim is to provide a common ground for virtualization solutions on top of Kubernetes. Also Kubevirt is a CNCF project.

**Which members of the community would benefit from your work?**
Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more kubevirt developers to utilize this project.

**Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?**
Yes.

https://github.com/kubevirt/kubevirt

**What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?**
Require access to arm64 servers. Still in planning phase of how many, but starting off one should be sufficient.

As such - no long term support need is currently envisioned.

**Please state your contributions to the open source community and any other relevant initiatives**

I have submit initial patch for enabling kubevirt on ARM. Also have discuss with kubevirt community about CI line on ARM. As kubevirt is a virtual machine orchestration tools, most tests need to running on bare metal server, a ARM server is necessary for its CI lane. For discuss details, please refer to https://github.com/kubevirt/kubevirt/pull/3415 

Please let me know if you need more information.
Thanks!!

**Comment by cayu53** [comment]
Happy to support. Will let Ed and others comment.
Thanks!

**Comment by vielmetti** [comment]
An invitation has been sent to Howard and a c2.large.arm server has been reserved.

**Comment by zhlhahaha** [comment]
Thanks a lot! @cayu53 @vielmetti

**Comment by vielmetti** [comment]
Noting https://github.com/rancher/harvester/issues/371 and that Kubevirt is a dependency for the new Harvester HCI from Rancher.

**Comment by pgmwoa** [comment]
We are in the process of getting the upgraded Mt Snow ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
@kalyxin02 @lubinsz @cayu53 @zhlhahaha 
One new Mt Snow (upgraded) has been reserved for the project as replacement for the one having provisioning issues. Please delete the old sever that is having issues so that Equinix team can reclaim that machine.

**Comment by zhlhahaha** [comment]
> @kalyxin02 @lubinsz @cayu53 @zhlhahaha One new Mt Snow (upgraded) has been reserved for the project as replacement for the one having provisioning issues. Please delete the old sever that is having issues so that Equinix team can reclaim that machine.

Thanks @pgmwoa , I have deleted the old server.

**Comment by pgmwoa** [comment]
Closing the ticket as the new system has been made available to the project.
