### ISSUE TITLE
Seastar, ScyllaDB - Works On Arm Sponsored

### ISSUE THREAD

**Issue by avikivity** [WorksOnArm/equinix-metal-arm64-cluster#244]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Avi Kivity <avi@scylladb.com>, ScyllaDB, CTO

Note that projects with two or more participants are preferred.

### Project Title and description

Two projects: Seastar, ScyllaDB

Seastar is a high performance C++ framework for asynchronous I/O oriented applications such as databases.
ScyllaDB is a NoSQL database using the Seastar framework.

Note: already running using a worksonarm ThunderX.

### Which members of the community would benefit from your work?

Users of Seastar (which include ScyllaDB, vectorized.io, Ceph) that wish to migrate to ARM
Users of ScyllaDB

### Is the code that you’re going to run 100% open source? 

Provide the URLs where it is located, or a Git repository.

100% open source

https://github.com/scylladb/seastar
https://github.com/scylladb/scylla

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

No

### What infrastructure (computing resources and network access) do you need?

Internet connectivity, 1TB storage.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.

Jenkins

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

Batching multiple commits. The CI system is not public.

Are you using a hosted CI system for some or all of your existing testing? 

Self-hosted.

### Please state your contributions to the open source community and any other relevant initiatives.

Original author of the Linux Kernel-based Virtual Machine (KVM), Seastar, ScyllaDB.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by vielmetti** [comment]
I updated the title to make it easier to track.

**Comment by avikivity** [comment]
Oops, thanks.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers

**Comment by avikivity** [comment]
I'm up and running. Many thanks.

**Comment by vielmetti** [comment]
Hi @pgmwoa , @avikivity  reached out to me regarding changes to the authorized users on this project - could you two sync up and see what needs to be done? thanks.

**Comment by avikivity** [comment]
I'd like to add @benipeled of our release engineering team as a co-administrator.

**Comment by pgmwoa** [comment]
> I'd like to add @benipeled of our release engineering team as a co-administrator.

I would need the email-id of the user for getting it added to the project.

**Comment by benipeled** [comment]
> I would need the email-id of the user for getting it added to the project.

beni.peled@scylladb.com
Thanks @pgmwoa

**Comment by pgmwoa** [comment]
> beni.peled@scylladb.com

Got it Thanks. Initiating the request to add user.

**Comment by pgmwoa** [comment]
> > [beni.peled@scylladb.com](mailto:beni.peled@scylladb.com)
> 
> Got it Thanks. Initiating the request to add user.

An invitation has been sent to join as a collaborator on the project. Please confirm.

**Comment by benipeled** [comment]
I got the invitation and manage to log-in,
Thanks,

**Comment by pgmwoa** [comment]
> I got the invitation and manage to log-in, Thanks,

Thanks, for confirming. I will close the ticket now.

**Comment by shipra-ps** [comment]
Hi Team,

We have sent an imp. communication to you on 25th Jul'24. Request your acknowledgement on the same.

Regards,
WoA Program Team
