### ISSUE TITLE
Bazel - Works On Arm Sponsored

### ISSUE THREAD

**Issue by philwo** [WorksOnArm/equinix-metal-arm64-cluster#271]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

- Philipp Wollermann, philwo@google.com, Google, Staff Software Engineer

### Project Title and description

**Bazel**

Bazel is an open-source build and test tool similar to Make, Maven, and Gradle. It uses a human-readable, high-level build language. Bazel supports projects in multiple languages and builds outputs for multiple platforms. Bazel supports large codebases across multiple repositories, and large numbers of users.

### Describe your use case for these machines

We are going to use the machine for two purposes:
- We will install the Buildkite Agent + Docker to let the machine process jobs from Bazel's CI. This will be used to build and test Bazel's official arm64 Linux releases.
- We will use the machine for interactive debugging and development purposes to improve Bazel's arm64 support.

### Which members of the community would benefit from your work?

All of Bazel's users who use Bazel on an arm64 machine.

### Is the code that you’re going to run 100% open source? 

Yes. The machine will be used for 100% open source work only. The entire source is on GitHub: https://github.com/bazelbuild/bazel

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not Sure

### What infrastructure (computing resources and network access) do you need?

We would be happy with continuous access to the machine proposed by our Works On Arm contact Manisha: "Mt Snow: 128GB (8x 16GB), 1TB SSD U.2, 1x 25GbE NIC".

### Describe / Name the continuous integration (CI) system for this project.

We are using Buildkite as our CI system. The CI dashboard is accessible at https://buildkite.com/bazel. The arm64 releases that we build using the machine are downloadable from our GitHub release pages, e.g. https://github.com/bazelbuild/bazel/releases/tag/4.1.0.

### Please state your contributions to the open source community and any other relevant initiatives.

I've been leading the Bazel open-source team at Google for a few years now, have given talks about building CI systems with Bazel and like to help port Bazel to other operating systems / architectures when I find the time. 😊

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers.

**Comment by philwo** [comment]
Hi,

I just wanted to let you know that I'm still in the progress of moving our setup from the old server to the new one. I'm sorry that it takes so long. I hope to finish by end of this week and would reply here then - is this ok?

Cheers,
Philipp

**Comment by vielmetti** [comment]
Thanks @philwo for the progress report! Just let us know here when you've sorted things out.

**Comment by pgmwoa** [comment]
@philwo Hope all is going on well with migration.

**Comment by philwo** [comment]
Hi,

Really sorry for the delay. Migration is done now and the new machine is so fast! More than twice as fast as the old one. 🥺 Thank you, this will really help us. Please feel free to recycle the old server.

Cheers,
Philipp

**Comment by philwo** [comment]
I just noticed that the old server (c2.large.arm, 147.75.73.154) still appears to be running and is visible in our account. Should I just delete it from our account or can you do this?

**Comment by vielmetti** [comment]
@philwo If you delete it, and then inform @pgmwoa , we'll get a ticket assigned to remove the reservation for that machine and it will be handled. Thanks!

**Comment by philwo** [comment]
@pgmwoa Server has been deleted. Thank you!

**Comment by pgmwoa** [comment]
@philwo Thanks. 
@vielmetti - I didn't have this machine under WoA as per 13 Sep 2021 Equinix hardware reservation data. Was it a reserved instance?

**Comment by philwo** [comment]
FWIW the old machine showed as "On Demand" when I looked at the dashboard today. The new machine is shown as "Reserved".

**Comment by vielmetti** [comment]
If it was "on demand" before, then our work here is done! Thanks @philwo @pgmwoa .

**Comment by philwo** [comment]
Hello,

as already discussed with @vielmetti via mail, I'd like to nominate my colleague @meteorcloudy (Yun Peng, pcloudy@google.com, Google, Senior Software Engineer) as the new contact person for Bazel's Works-on-ARM project.

He will add a comment here soon with details about requesting one more machine after a discussion with our contact at ARM.

Thanks,
Philipp

**Comment by meteorcloudy** [comment]
Hi,

after meeting with our contacts at ARM, we would like to request one more Works-on-ARM machine for Bazel CI.

The machine will be used for the regular [Bazel postsubmit](https://buildkite.com/bazel/bazel-bazel) on Linux ARM64 platform, which runs the entire Bazel test suite. All Bazel users on ARM64 will benefit from better test coverage.

We couldn't use the existing machine because in our current CI setup we can't run trusted jobs (= building release binaries) and untrusted jobs (= running the test suite) on the same machine.

Thanks,
Yun

**Comment by pgmwoa** [comment]
> Hi,
> 
> after meeting with our contacts at ARM, we would like to request one more Works-on-ARM machine for Bazel CI.
> 
> The machine will be used for the regular [Bazel postsubmit](https://buildkite.com/bazel/bazel-bazel) on Linux ARM64 platform, which runs the entire Bazel test suite. All Bazel users on ARM64 will benefit from better test coverage.
> 
> We couldn't use the existing machine because in our current CI setup we can't run trusted jobs (= building release binaries) and untrusted jobs (= running the test suite) on the same machine.
> 
> Thanks, Yun

Hi,

We are processing your request. 

Regards
Manisha
