### ISSUE TITLE
Zig - Works On Arm Sponsored

### ISSUE THREAD

**Issue by andrewrk** [WorksOnArm/equinix-metal-arm64-cluster#288]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Andrew Kelley
andrew@ziglang.org
Zig Software Foundation
President & Lead Developer

### Project Title and description

Zig Programming Language

### Describe your use case for these machines

Testing various things on ARM

### Which members of the community would benefit from your work?

everybody

### Is the code that you’re going to run 100% open source? 

https://github.com/ziglang/zig/

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Yes, we support all versions of arm

### What infrastructure (computing resources and network access) do you need?

ssh access to various ARM CPUs

machines powerful enough to build LLVM.

### Describe / Name the continuous integration (CI) system for this project.

N/A

Will these machines be exclusively used for CI purposes?

No

Please share a public URL of the CI dashboard (if applicable).

N/A

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes

### Please state your contributions to the open source community and any other relevant initiatives.

Contributions to:
 * LLVM, LLD, Clang
 * Wine
 * QEMU
 * GDB
 * DWARF Specification

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Logo in the infrastructure section of https://ziglang.org/zsf/

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Please modify the Project name as appropriate. It is showing "**Project name** - Works on Arm Sponsored"

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

**Comment by pgmwoa** [comment]
@andrewrk  The Altra machine allocated to the project has not yet been deployed. Please confirm project's migration plans.

**Comment by pgmwoa** [comment]
@andrewrk @daurnimator - Please update.

**Comment by shipra-ps** [comment]
Hi Andrew,

I had been trying to reach out to you to update that your duration for the server availability has already expired. 

Can you please provide us an update on your current server usage and future plans for the project builds on ARM?

Regards,
Shipra Snehi
WoA Program Team
