### ISSUE TITLE
Kubevirt - Works On Arm Sponsored

### ISSUE THREAD

**Issue by zhlhahaha** [WorksOnArm/equinix-metal-arm64-cluster#289]
Name, email, company, job title
Howard Zhang, howard.zhang@arm.com, Arm, senior software engineer

Project Title and description
KubeVirt (https://github.com/kubevirt/kubevirt) is a virtual machine management add-on for Kubernetes. The aim is to provide a common ground for virtualization solutions on top of Kubernetes. Also Kubevirt is a CNCF project.

Describe your use case for these machines
For kubevirt CI test. Currently, we have one Altra Mt Snow server for this project, we need one more server to enable live-migration e2e test.

Which members of the community would benefit from your work?
Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more kubevirt developers to utilize this project.

Is the code that you’re going to run 100% open source?
Yes.

https://github.com/kubevirt/kubevirt

What infrastructure (computing resources and network access) do you need?
one more new Altra Mt Snow

Describe / Name the continuous integration (CI) system for this project.
prow and kubernetes

Please state your contributions to the open source community and any other relevant initiatives.
Enable kubeVirt on ARM64 and related CI works

**Comment by zhlhahaha** [comment]
cc: @justin-he

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. You should be able to see the new system in the reserved systems list.
