### ISSUE TITLE
MariaDB Server - Works On Arm Sponsored

### ISSUE THREAD

**Issue by cvicentiu** [WorksOnArm/equinix-metal-arm64-cluster#291]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Vicențiu Ciorbaru
vicentiu@mariadb.org
MariaDB Foundation
Senior Software Engineer, Team Lead

Note that projects with two or more participants are preferred.
The MariaDB Foundation has a team of developers in charge of maintaining the collaboration between the community and the core developers of MariaDB Server. For the whole team see:
https://mariadb.org/about/#team

## MariaDB Server ##
MariaDB Server is the most popular alternative to MySQL.  Developed by the original authors of MySQL, it is default in most of the major Linux distributions and runs on a multitude of platforms, including X86, ARM, PowerPC, s390z, MIPS and others.

### Describe your use case for these machines
In order to ensure the high quality of MariaDB Server that distributions and users expect, we have set up a continuous integration and testing platform at https://buildbot.mariadb.org. The platform builds and tests MariaDB for every push and pull request that developers and contributors do.

The main purpose  for the ARM machines is to provide timely feedback on correctness of a patch (testing wise) as well as provide packages that are later distributed via https://mariadb.org/download to the whole community. Buildbot also functions as a launch pad for other community projects to integrate testing with the newest MariaDB releases. Built packages are saved on https://ci.mariadb.org. 

### Which members of the community would benefit from your work?
All users of MariaDB Server. All projects that rely on MariaDB Server to function properly. A few noteworthy examples: Wordpress, PHPMyAdmin, cpanel, Django, etc.

### Is the code that you’re going to run 100% open source? 
Yes, the MariaDB Server code is licensed under GPL v2.

Provide the URLs where it is located, or a Git repository.
https://github.com/MariaDB/server

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
MariaDB Server benefits from testing on the newest ARM hardware as that is where we can enable the latest optimizations and is what data centers will end up providing. As such, any version of ARM is acceptable, but newer versions are preferred.

### What infrastructure (computing resources and network access) do you need?

Based on our current development flow, we have estimated that we will require approximately 120 ARM cores, where each core has between 2-4GB of RAM assigned to it. For example a 4core VM will need at least 8 (preferably 16GB) of RAM. Storage is not critical, however 100GB / virtual machine is preferable (1-2TB in total), depending on how the cores are split.

We also are ok (in fact prefer) bare metal machines.

The hardware is meant to test an average of 28 pushes per day, 7 days/week. Network speed is not critical, however the build process needs to upload artifacts of around 1GB in size (ideally for every push). Most of our infrastructure is located in Europe, but we have build servers located in US and Asia. As such, location is not important, but Europe is preferred.

The preferred setup is for us to receive root access to the machines, with the ability to set up a wireguard connection to https://buildbot.mariadb.org. After that we can take care of managing the machines ourselves. The preferred OS is Debian 11 at this point.

Note that the hardware numbers above are the ideal scenario. We will accept any subset of the above, but the numbers presented will enable us to test fully on all our supported distributions.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

The MariaDB Foundation is in charge of ensuring the continuity of MariaDB Server and all the underlying infrastructure needs. We will only require support should we lose network access to any of the machines and require some form of a recovery console.

### Describe / Name the continuous integration (CI) system for this project.
We are using Buildbot as the CI system. We are working with the Buildbot developers to also extend the system to cover a few of our more specific needs. We also have a work-in progress documentation of our setup here:
https://mariadb.com/kb/en/about-buildbot/

Will these machines be exclusively used for CI purposes?
Most probably yes, but they may be at times used by developers directly to reproduce certain bugs.

Please share a public URL of the CI dashboard (if applicable).
https://buildbot.mariadb.org

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure
In general yes, as long as the logo is one from:
https://mariadb.org/logo
however let us get in touch about the details separately.

If No / Not Sure, Please share the relevant contact.
vicentiu@mariadb.org

### Please state your contributions to the open source community and any other relevant initiatives.

Almost all of my professional career has been working in Open Source.

I have been involved in developing code for MariaDB for more than 8 years. Additionally I mentor students as part of Google Summer of Code, some of which have stayed in the Open Source community. Additionally I have contributed to Open Source projects such as Samba and Chromium (about:tracing functionality) and indirectly to Buildbot.

MariaDB Foundation also has taken over maintaining the Official Docker images for MariaDB, which were previously maintained by the community. We still keep a close discussion with community maintainers and we allocate more resources to ensure that all the capabilities of MariaDB are exposed via Docker images and that upgrades are as painless as possible.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

We have a dedicated page on our CI page, specifically for hardware sponsors, we are more than willing to also post "Works on Arm" or other related logo on that page. We also maintain a YouTube channel https://www.youtube.com/c/MariaDBFoundation
where we can post specific videos related to MariaDB on ARM. Twitter posts are also possible from the https://twitter.com/mariadb_org account.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by cvicentiu** [comment]
Note that MariaDB has previously had ARM hardware donated and the person in charge was Daniel Bartholomew. (dbart@mariadb.com). This issue is a response to the note that the older hardware is being decommissioned.

The MariaDB Foundation, can take over maintaining the  newer ARM hardware (with me as the contact person) and ensure it is integrated properly in the CI system.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by cvicentiu** [comment]
Sending a message here just in case the hardware is ready and somehow I did not get the email.

If it's not yet, we're eagerly waiting for it :)

**Comment by pgmwoa** [comment]
There is a little delay, will update you as soon as it is done. Thanks for your patience.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.

**Comment by vielmetti** [comment]
@cvicentiu The server has been allocated to the project. If you would be so good as to let me and @pgmwoa know when it's all the way working and tested, I'll start the process of reclaiming the remainder of the old Qualcomm systems.

**Comment by pgmwoa** [comment]
Closing the ticket as old machines have been reclaimed.

**Comment by shipra-ps** [comment]
Hi @cvicentiu ,

We have sent one imp communication over email on 25th Jul'24. Request you to acknowledge the same.

**Comment by cvicentiu** [comment]
Ack, replied.
