### ISSUE TITLE
SONIC ARM switch pipeline enablement

### ISSUE THREAD

**Issue by kielfriedt** [WorksOnArm/equinix-metal-arm64-cluster#293]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

Proposals is to provide Microsoft SONIC team pool resources for nightly and per-PR build validation. Currently building is completed on emulation and resources are needed to compete with x86 build pipelines. creation of  pipelines for KVM builds on arm64 are in progress and will be resource intensive.

### Name, email, company, job title

Note that projects with two or more participants are preferred.

Kiel Friedt kiel.friedt@arm.com ARM Principal Solutions Engineer
Allaukik Abhishek Allaukik.Abhishek@arm.com  ARM Principal Solutions Engineer

### Project Title and description

SONIC ARM switch enablement

### Describe your use case for these machines

Creating CI/CD pipeline for SONIC NOS under AZURE. Porting was originally on the  N1SDP to ONIE and then onto SONIC. The Microsoft team has requested CI/CD for building components and services under SONIC. SONIC on ARM is now gaining traction. Building larger components and new build paths that are comparable to the x86 systems is being developed and seen. The SONIC team is asking for resources to build out their pipeline and push arm to a first class citizen. Currently a small group of items are built under QEMU. This takes days to complete.

### Which members of the community would benefit from your work?

SONIC is a popular NOS, providing CI/CD on ARM would allow quick deployment on new and existing ARM switching equipment. Thus leading to a increase in adoption.

### Is the code that you’re going to run 100% open source? 

yes 

Provide the URLs where it is located, or a Git repository.

https://github.com/Azure/SONiC
https://github.com/Azure/sonic-buildimage
 
### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No

### What infrastructure (computing resources and network access) do you need?

Current build pipelines are using very large machines with nested virtualization. Current x86 build pool consists of many servers, ~800 cores with tbs of memory. They are trending to 1000+ cores by EOY. Most of SONICS build process is disk focused just FYI. SONICS  has requested  6+ servers but 2-3 will work until pipelines are fully built out. (ETA will be updated shortly.) Depending on performance needs we will request more. 

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

I would expect this to be a long term effort since ARM switch equipment is a small but growing market. New build pipelines will open up many more opportunities especially with ONIE enabled switches and system ready.

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes?

Yes

Please share a public URL of the CI dashboard (if applicable).

[Pipelines - Runs for Azure.sonic-buildimage.official.centec-arm64](https://dev.azure.com/mssonic/build/_build?definitionId=140)
[Pipelines - Runs for Azure.sonic-buildimage.official.marvell-armhf](https://dev.azure.com/mssonic/build/_build?definitionId=141)

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

If No / Not Sure, Please share the relevant contact.
Not sure, i will ask in our meeting next week.

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

Kiel is a principle support engineer focused on Cloud/5G/network enablement. In the past working as a windows kernel developer and has experience on many security projects within the telecom space.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
This project requirements are 8core 8gb and 500gb per instance and require more than 2TB, which cannot be supported on current WoA infrastructure. Hence as discussed with project requester, closing this ticket.
