### ISSUE TITLE
The gVisor-ci server is down.

### ISSUE THREAD

**Issue by avagin** [WorksOnArm/equinix-metal-arm64-cluster#295]
We can access it via ssh. Could you check what is going on there and reboot it? Thanks.

(edit)

- [ ] Related to #290

**Comment by vielmetti** [comment]
Please be in touch with @pgmwoa directly for assistance on this.

**Comment by avagin** [comment]
@pgmwoa what is a good way to reach you directly?

**Comment by pgmwoa** [comment]
@avagin pls try shutdown -r now on systemd

cc: @justin-he, @zhlhahaha

**Comment by pgmwoa** [comment]
Closing the ticket as @avagin can access the new ARM server for gVisor project.
cc: @justin-he, @zhlhahaha
