### ISSUE TITLE
Julia Language - Works On Arm Sponsored

### ISSUE THREAD

**Issue by Keno** [WorksOnArm/equinix-metal-arm64-cluster#297]
This was previously approved in #247, but a re-submit was requested, so I'm submitting that here.

### Name, email, company, job title

Keno Fischer, keno@alumni.harvard.edu, Julia Language, Core Contributor
Viral Shah, viral@mayin.org, Julia Language, co-creator (@ViralBShah)
Elliot Saba, staticfloat@gmail.com, Julia Language, Core Contributor (@staticfloat)

### Project Title and description

The Julia Programming Language

### Describe your use case for these machines

Pre and Post-Commit CI for Aarch64

### Which members of the community would benefit from your work?

All users of the Julia programming langauge.

### Is the code that you’re going to run 100% open source? 

Yes, https://github.com/JuliaLang/julia and dependencies.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Yes, ideally with ARMv8.4a for rr support.

### What infrastructure (computing resources and network access) do you need?

Long term access, for CI, ideally at least 64 cores to match CI throughput of other major platforms.

### Describe / Name the continuous integration (CI) system for this project.

Julia CI is run through Buildkite and buildbot (legacy). The CI machine would run one buildkite worker per 8 CPU cores. CI jobs from Julia are scheduled to available workers.

Buildkite dashboard: https://buildkite.com/julialang/julia-master
Buildbot dashboard: https://build.julialang.org/#/

Note that Aarch64 support is currently provided elsewhere, but will be ending within the week, hence our intention to migrate to this hardware.

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes, in accordance with the Julia Language logo usage policy. In particular, it may be used to refer to the language and reference ARM support.

### Please state your contributions to the open source community and any other relevant initiatives.

The Julia language project and community is one of the largest open source communities and particular focuses on advancement of science and scientific education. For more information, see julialang.org.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources
