### ISSUE TITLE
ELRepo - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jaboutboul** [WorksOnArm/equinix-metal-arm64-cluster#298]
### Name, email, company, job title

Jack Aboutboul, jack@almalinux.org, AlmaLinux Community Manager
Akemi Yagi, contact@elrepo.org, ELRepo Maintainer

### Project Title and description

ELRepo is an RPM repository for Enterprise Linux packages. ELRepo supports Red Hat Enterprise Linux (RHEL) and its derivatives, and focuses on providing alternative kernels (latest mainline and long-term), hardware related packages as well as filesystem drivers, graphics drivers, network drivers, sound drivers, webcam and video drivers, which are typically not available in the upstream tree. Many thousands of organization and users around the world rely on ELRepo to enable functionality which would not otherwise be available on RHEL and it's derivatives.

### Describe your use case for these machines

Currently ELRepo only builds for x86_64. These machines will be used to in our efforts to build the project's packages for aarch64 thereby enabling aarch64 as supported platform for the project.

### Which members of the community would benefit from your work?

The last published stats (https://elrepoproject.blogspot.com/2017/01/elrepo-statistics-2017.html) show over a million users of the repo in 2017. This has significantly increased since then and ELRepo has become an integral part of the landscape for EL-family distributions. As aarch64 continues to grow in popularity, we expect this to significantly help quite a large number of aarch64 users who choose to run on aarch64.

### Is the code that you’re going to run 100% open source? 

Yes. All code is available on Github at https://github.com/elrepo and included in the https://elrepo.org/linux/elrepo/ under the specific release subfolder then under the SRPMS folder. For example, for EL8 is https://elrepo.org/linux/elrepo/el8/SRPMS/.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details.

Yes. This is needed in order to ensure that kernel tests and builds successfully the ARMv8.2 enhancements such as SPE, SVE, etc.

### What infrastructure (computing resources and network access) do you need?

Preferably 2 x dual socket Altra machines.

### Describe / Name the continuous integration (CI) system for this project.

Most builds are done locally on the machines used as builder nodes in a tmpfs mock folder using the `mock` rpm build tools.

Please share a public URL of the CI dashboard (if applicable).

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Need to bring this up to maintainers but I don't see why there would be any hesitation.

### Please state your contributions to the open source community and any other relevant initiatives.

ELRepo is a significant part of the EL-family landscape. It has been enabling out-of-upstream functionality via kernels, kmods, and drivers for millions of users around the worls.

## Important reminders and logistics

Got it!

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.

**Comment by shipra-ps** [comment]
Hi Team, 

I have sent one important communication to you over email on 10th Jul'24. Request you to check that and acknowledge.

Regards,
Shipra Snehi
WoA Program Team
