### ISSUE TITLE
Tools porting and optimization for new processor - Works On Arm Sponsored

### ISSUE THREAD

**Issue by vince75** [WorksOnArm/equinix-metal-arm64-cluster#299]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Vincent Casillas, vincent.casillas@sipearl.com, SiPearl, VP R&D SW
Romain Dolbeau, romain.dolbeau@sipearl.com, SiPearl, HPC Fellow
Olivier Gautherot, olivier.gautherot@sipearl.com, SiPearl, SW Engineer
Wijdane Dimoqrati, wijdane.dimoqrati@sipearl.com, SiPearl, SW Engineer
Moursal Mahamoud-Ali, moursal.mahamoud-ali@sipearl.com, SiPearl, HPC Benchmark Engineer

Note that projects with two or more participants are preferred.

### Project Title and description
Porting and optimizing some tools for HPC specific use cases

### Describe your use case for these machines
We will use those platforms to work on open source projects and prepare the patches needed to support our processor when it will be available.

### Which members of the community would benefit from your work?
GDB, LLVM, GCC, Mathematical libraries

### Is the code that you’re going to run 100% open source? 
Yes most of the code will be 100% open source 

Provide the URLs where it is located, or a Git repository.
https://www.gnu.org/software/gdb/current/
https://github.com/oneapi-src/oneDNN
https://github.com/oneapi-src/oneCCL
https://github.com/open-mpi/ompi
https://github.com/llvm/llvm-project
https://gcc.gnu.org/git/gcc.git

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Yes, we need to also perform some tests using Arm Instruction Emulator (ArmIE) to emulate SVE and perform some tests on simulated ARMv8.4 or later.

### What infrastructure (computing resources and network access) do you need?
It is a long term project where we will need this machine to run some CI jobs as well.
3 dual socket Ampere Altra platform, one or two for development and one for CI. 

The preferred setup is for us to receive bare metal machine with root access to setup the machines ourself. After that we can take care of managing the machines ourselves. The preferred OS is Ubuntu 20.x.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.
CI could be Gitlab, not yet fully defined.

Will these machines be exclusively used for CI purposes?
No, they will be used also for development 

Please share a public URL of the CI dashboard (if applicable).

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

If No / Not Sure, Please share the relevant contact.
Not Sure, I will investigate internally

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!
SiPearl is a silicon manufacturer developing an HPC processor with ARM Neoverse cores and we need to prepare the support of our processor for different tools and make sure we will provide to open source community all the patches needed.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.
