### ISSUE TITLE
ProjectFP/Various OSS - Works On Arm Sponsored

### ISSUE THREAD

**Issue by colemickens** [WorksOnArm/equinix-metal-arm64-cluster#300]
### Name, email, company, job title

Cole Mickens, cole.mickens@gmail.com, (unannounced, TBD), Founder,SoftwareEngineer,Whatever

### Project Title and description

I'm a developer, I've been using ARM instances on Packet.net/com/EquinixMetal for years... or had been.

### Describe your use case for these machines

Off the top - I don't necessarily need free/subsidized instances. I just need access to the ARM SKUs again in the API.

That having been said, 99% of my usage of Equinix Metal machines is for exclusively open source work -> either upstream work on NixOS/nixpkgs, Mobile NixOS (pinebook, pixel 3, etc), or my own personal hybrdi-architecture nixos config that is shared around in the Nix community.

I am *also* working on a "product" that will be open-source, but its years away at this pace. I mostly just need access back so that I can do various maintenance tasks for NixOS / Mobile NixOS / nixpkgs-wayland / Rust / etc.

### Which members of the community would benefit from your work?

Some random NixOS users might. My future project's target market is nerds who want to control the degree to which they self-host their own services/data. I suppose there might be a nice story here around ARM being useful for cheap cloud hosting and low-temp/low-power self-home-hosting.

### Is the code that you’re going to run 100% open source? 

For all intents and purposes yes, there might be some in-progress code that isn't shared, but that would be incidental.

### Provide the URLs where it is located, or a Git repository.

N/A yet, otherwise it would be **cole-mickens/nixcfg**, **nixos/nixpkgs**, **nixos/mobile-nixos**.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure, but I doubt it.

### What infrastructure (computing resources and network access) do you need?

I'd like access to all available ARM skus on Equinix Metal, since I've been using them for years anyway.

I do not need on-going support, at least not in terms of ARM support -> as long as the OS boots, I'm fine.

### Describe / Name the continuous integration (CI) system for this project.

I decline to answer this because it seems inappropriate.

### Will these machines be exclusively used for CI purposes?

Again, I decline to answer -- these questions are making me nervous. Is Ampere insecure about the quality of results from their processors or why on Earth is this information needed? Is it just about being able to reclaim instances if needed?

### Please share a public URL of the CI dashboard (if applicable).

N/A.

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

I'm not qualified or authorized to speak on behalf of the projects I've mentioned that I contribute to. `nixpkgs-wayland` does not have a logo. My future project is too early to bother with, and does not have a logo. But if ARM wants to talk about me in any capacity, I wouldn't have any problems with that.

### Please state your contributions to the open source community and any other relevant initiatives.

I've been kicking the tires on Packet + ARM instances for literally years, I'd really just like to get back to work.

If it would somehow help my case, I'm working on the ideal Equinix Metal + Nix + Terraform setup. My Metal, Terraform, and NixOS configurations are all specified in Nix, and terraform is configured statically. It's very reliable (presuming Metal APIs work and I have access to the SKU I need 😉).

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

**CM: That's fine - I could put it in READMEs or something if I were indeed getting it free (which again, I don't necessarily need)**

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!

**CM: ACK: I am very diligent about leaving instances running since ... I'm used to paying for them.**

In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
@colemickens, As discussed, closing the ticket for now. You can reopen it as and when you are ready with updated information, future plans. Thanks.
