### ISSUE TITLE
Raspbian Addons - Works On Arm Sponsored

### ISSUE THREAD

**Issue by ryanfortner** [WorksOnArm/equinix-metal-arm64-cluster#301]
### Project

Raspbian Addons is an APT repository for Raspberry Pi computers, containing open-source software not in the Pi Foundation's repositories.

### Describe your use case for these machines

These machines will be used for testing and development of debian repositories for arm.

### Which members of the community would benefit from your work?

Any members of the Raspberry Pi/ARM SBC community who are in need of updated and working software.

### Is the code that you’re going to run 100% open source? 

Every part of Raspbian Addons is open-source, including its packages and its [scripts](https://github.com/raspbian-addons/scripts)

### What infrastructure (computing resources and network access) do you need?

We are requesting continuous ongoing support for the following:

- Hosting the Raspbian Addons repository and its branches
- Providing an environment for testing and development of the software in Raspbian Addons
- SSH access to the computing resources 

### Please state your contributions to the open source community and any other relevant initiatives.

I am an active maintainer of the [Raspbian Addons repository](https://github.com/raspbian-addons), and I am interested in the ARM community and the development of software with ARM support.

Thank you for your consideration of this request!

**Comment by hmsjy2017** [comment]
Any progress? @pgmwoa @vielmetti  @bhumikpatel

**Comment by pgmwoa** [comment]
@hmsjy2017 @ryanfortner I have shared some updates in the email to ryankfortner@gmail.com. Please refer to email dated 21st Dec 2021 and have resend again today i.e., on 10th Jan 2022 at emails-ids ryankfortner@gmail.com & i@iamsjy.com.

**Comment by pgmwoa** [comment]
> @pgmwoa Could you send me that email once again? I didn't receive it due to misconfigured domain mailbox.

Done. Pls confirm

**Comment by hmsjy2017** [comment]
@pgmwoa I think 4 cores and 8G memory should be enough. Since we need to compile and develop, the disk space needs to be large enough (preferably more than 60GB). Also, we require the VM to support IPv4, preferably one that is accessible from the outside. Currently, we intend to use GitHub's self-hosted runner for continuous integration.

**Comment by pgmwoa** [comment]
@hmsjy2017 @ryanfortner , as communicated earlier we do not have systems available in inventory for allocation at this time. Hence keeping the request on hold.

**Comment by hmsjy2017** [comment]
@pgmwoa Could you tell me when the systems will be available?

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same.
