### ISSUE TITLE
QuTiP - Works On Arm Sponsored

### ISSUE THREAD

**Issue by hodgestar** [WorksOnArm/equinix-metal-arm64-cluster#302]
### Name, email, company, job title

Simon Cross, simon.cross@riken.jp, Riken, Technical Specialist

The QuTiP project is run by an admin team of 9 people and a scientific advisory board of 5 people (14 in total). Both span multiple continents and institutions.

### Project Title and description

QuTiP

QuTiP is open-source software for simulating the dynamics of closed and open quantum systems.

### Describe your use case for these machines

The ARM architecture is increasingly prevalent in HPC, an environment in which QuTiP is regularly used. We would like to be able to run continuous integration on ARM so that we know the platform is well supported and don't introduce regressions for users accidentally.

### Which members of the community would benefit from your work?

Everyone who would like to run QuTiP on ARM (e.g. on the Fugaku supercomputer, to give one current set of users).

### Is the code that you’re going to run 100% open source? 

Yes. https://github.com/qutip/qutip.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

ARMv8.2 is not an absolute requirement, but it would be nice to match the ARM processors used in HPC environments. There is significant value in testing on any environment though.

### What infrastructure (computing resources and network access) do you need?

We would like ongoing support. We can already compile on ARM, but it would be very helpful to be able to run continuous integration tests.

A single machine that we can run integration tests on would be sufficient. Being able to run multiple threads and processes in order to test various parallelization options would be useful.

We only need network access for installing dependencies -- QuTiP itself doesn't not require network access.

### Describe / Name the continuous integration (CI) system for this project.

Name: GitHub Actions

Will these machines be exclusively used for CI purposes? Yes

Please share a public URL of the CI dashboard (if applicable). https://github.com/qutip/qutip/actions/workflows/tests.yml

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes, but please ask me before doing so and I can get formal approval from the whole admin team.

### Please state your contributions to the open source community and any other relevant initiatives.

I work full-time on QuTiP. Previously I worked full-time on HPy. I founded and still help run the Python Software Society of South Africa and PyConZA. I've been doing open source work for a long time.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by hodgestar** [comment]
Thank you!

**Comment by pgmwoa** [comment]
@hodgestar , as communicated we do not have systems available in inventory for allocation at this time. Hence keeping the request on hold.

**Comment by hodgestar** [comment]
Ping! We'd still like to be considered when / if machines become available.

**Comment by pgmwoa** [comment]
Closing the ticket as there is no further activity. Thanks for your contribution.
