### ISSUE TITLE
Citadel - Works On Arm Sponsored

### ISSUE THREAD

**Issue by AaronDewes** [WorksOnArm/equinix-metal-arm64-cluster#304]
### Name, email, company, job title

Aaron Dewes, aaron.dewes@protonmail.com, student

### Project Title and description

Citadel makes it possible for anyone to run a personal web server and bitcoin node (non-mining, we're not promising anyone to get rich, it's only for storing Bitcoin, not earning them). It provides an easy app store so everyone can install any app they want (with support for 3rd party apps).

Some apps include:

- Nextcloud
- Photoprism
- SpigotMC (A minecraft server)
- Synapse

### Describe your use case for these machines

We're planning to host a [GitHub actions runner](https://github.com/actions/runner) on this, and use it to build Docker containers for various FOSS apps.

### Which members of the community would benefit from your work?

Everyone running Citadel on arm64, as well as projects looking to package their app for Citadel because we can help them dockerize their apps. These docker containers can be used by anyone, so the communities of projects we dockerize benefit as well.

### Is the code that you’re going to run 100% open source? 

We're planning to host a [GitHub actions runner](https://github.com/actions/runner) on this, and use it to build Docker containers for various FOSS apps, including these:

- https://github.com/runcitadel/manager
- https://github.com/runcitadel/middleware
- https://github.com/runcitadel/lnbits-legends
- https://github.com/runcitadel/element-web
- https://github.com/runcitadel/lightning-address-v2
- https://github.com/runcitadel/docker-electrs
- https://github.com/runcitadel/docker-snowflake
- https://github.com/runcitadel/docker-loop

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No

### What infrastructure (computing resources and network access) do you need?

I'm not sure

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes? Yes

[GitHub actions runner](https://github.com/actions/runner)

### Does the project allows the use of your project logo on ARM's developer website freely?

Yes

### Please state your contributions to the open source community and any other relevant initiatives.

I've made small cotributions to [Yarn](https://github.com/yarnpkg/berry/commit/47f88b6af1a7f033bd9189cde3247d9baa990967) and [Qt](https://github.com/qt/qtwayland/commit/7d1debe004cbf3e0a1561dd234fbedab9b2ab3f9), as well as [Probot](https://github.com/probot/probot/commits/?author=AaronDewes) (especially to [its website](https://github.com/probot/probot.github.io/commits/?author=AaronDewes))

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request.

**Comment by pgmwoa** [comment]
@AaronDewes , as communicated we do not have systems available in inventory for allocation at this time. Hence keeping the request on hold.
