### ISSUE TITLE
Pipy - Works On Arm Sponsored

### ISSUE THREAD

**Issue by naqvis** [WorksOnArm/equinix-metal-arm64-cluster#305]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Ali Naqvi, alinaqvi@flomesh.io, Flomesh Ltd., Evangelist

Note that projects with two or more participants are preferred.

### Project Title and description

**Pipy** is an [open-source](https://github.com/flomesh-io/pipy), lightweight, high-performance, modular, programmable, cloud-native network stream processor that is ideal for a variety of use-cases ranging from (but not limited to) edge routers, load balancers & proxy solutions, API gateways, static HTTP servers, service mesh sidecars, and other applications.

### Describe your use case for these machines

Compilation and testing various things on ARM

### Which members of the community would benefit from your work?

Everybody

### Is the code that you’re going to run 100% open source? 

Yes fully open source.

Provide the URLs where it is located, or a Git repository.

[https://github.com/flomesh-io/pipy](https://github.com/flomesh-io/pipy)

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Yes, we support all versions of arm

### What infrastructure (computing resources and network access) do you need?

ssh access to various ARM CPUs
machines powerful enough to compile and build via clang.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

continuous long term support is needed.

### Describe / Name the continuous integration (CI) system for this project.

Github Actions 

Will these machines be exclusively used for CI purposes?

Yes and also for running test suites.

Please share a public URL of the CI dashboard (if applicable).

[https://github.com/flomesh-io/pipy/actions](https://github.com/flomesh-io/pipy/actions)

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes

### Please state your contributions to the open source community and any other relevant initiatives.

Long time open source contributor and evangelist. Contribution to
* Pipy
* Kong
* Kubernetes
* Open service mesh
* Crystal

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by naqvis** [comment]
Appreciate any review and/or comments.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same.
