### ISSUE TITLE
Emscripten - Works On Arm Sponsored

### ISSUE THREAD

**Issue by sbc100** [WorksOnArm/equinix-metal-arm64-cluster#306]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Sam Clegg, sbc@chromium.org, Google, SWE

### Project Title and description

Emscripten -  a complete compiler toolchain to WebAssembly, using LLVM, with a special focus on speed, size, and the Web platform.

### Describe your use case for these machines

We want to be able to continuously compile and publish arm64/linux binaries alongside the x86_64 ones: See https://github.com/emscripten-core/emsdk/issues/547

### Which members of the community would benefit from your work?

Any developers wanting to use emscripten on arm-based hardware.  The bug above contains message from several such developers.

### Is the code that you’re going to run 100% open source? 

Yes:

https://github.com/emscripten-core/emscripten
https://github.com/llvm/llvm-project
https://github.com/WebAssembly/binaryen

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure.  Probably not.

### What infrastructure (computing resources and network access) do you need?

We are looking for a long term CI machine that can continuously build and publish arm64 binaries.

### Describe / Name the continuous integration (CI) system for this project.

For the sdk builders we currently use chromium infrstructure:
https://ci.chromium.org/p/emscripten-releases/g/main/console

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Not Sure, Please share the relevant contact.

### Please state your contributions to the open source community and any other relevant initiatives.

I work on the WebAssembly backend of llvm and on the emscripten compiler driver.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by otterley** [comment]
I think we can close this, as Emscripten is being built automatically for Arm64 via EC2.

**Comment by pgmwoa** [comment]
> I think we can close this, as Emscripten is being built automatically for Arm64 via EC2.

Thanks for the update. Closing the ticket.
