### ISSUE TITLE
LLVM/ARM - Works On Arm Sponsored

### ISSUE THREAD

**Issue by anmparal** [WorksOnArm/equinix-metal-arm64-cluster#307]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Name: Anmol P. Paralkar
Email: anmparal@cisco.com
Company: Cisco Systems
Job title: Software Engineering Technical Leader

Note that projects with two or more participants are preferred.

### Project Title and description
LLVM/ARM: Code generation, Performance & Code Size Optimization, do daily native build on ARM64 of LLVM.Org trunk sources and monitor numbers - flagging failures as they happen, on regression suite.

### Describe your use case for these machines
Fix ARM64 code generation & optimization (time & space)  bugs. Could be compile time issues generating ARM code, as well:
e.g: "[AArch64] Extremely slow code generation for series of function calls/addition" https://bugs.llvm.org/show_bug.cgi?id=51147 (totally fine on x86_64)

### Which members of the community would benefit from your work?
All LLVM/ARM users.

### Is the code that you’re going to run 100% open source? 

Yes, 100% open source.

Provide the URLs where it is located, or a Git repository.

https://github.com/llvm/llvm-project.git

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure. But ARM64. Will add details once I know more.

### What infrastructure (computing resources and network access) do you need?

I need a linux box on which I will be able to build the entire LLVM compiler & tools; install/request pre-requisites if missing.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Continuous, daily, ongoing: llvm.org trunk

### Describe / Name the continuous integration (CI) system for this project.

git? Not sure what you mean ...

Will these machines be exclusively used for CI purposes?

I want to be able to do native LLVM compiler & tools builds, fix bugs, make code-size and performance improvements.

Please share a public URL of the CI dashboard (if applicable).

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Not Sure, but see: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiK6PappNP3AhVYlWoFHRG6Cx8QFnoECA0QAQ&url=https%3A%2F%2Fwww.arm.com%2F-%2Fmedia%2Fglobal%2Fmarkets%2Finfrastructure%2FArm_White_Paper_Cisco_EmpowerTheEdge.pdf%3Frevision%3Db10aabe9-48d8-4e7f-8706-d472b1477ac2%26hash%3DB1827FA859835259229BCB0A1C15A5D8968A9F83&usg=AOvVaw2FDnCpDk1Tn6biweRj9Mqa

If No / Not Sure, Please share the relevant contact.

Please let me know who is the ARM liaison/point-of-contact in Cisco and I'll be sure to contact them, thanks.

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

https://reviews.llvm.org/D28075
https://reviews.llvm.org/D28121
https://reviews.llvm.org/D28186

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Please let me know whom to contact within Cisco for ARM matters, thanks.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Please update the Project name.

**Comment by vielmetti** [comment]
+1 for perf improvements in LLVM, that will be welcomed.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same.

**Comment by anmol-paralkar** [comment]
Hello, I am changing employers; thank you so much for making this resource available to me.
Deeply appreciated!
Best wishes & Regards,
Anmol.
