### ISSUE TITLE
Open Infrastructure Foundation(OpenStack) - Works On Arm Sponsored

### ISSUE THREAD

**Issue by kevinzs2048** [WorksOnArm/equinix-metal-arm64-cluster#308]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Kevin Zhao, kevin.zhao@linaro.org, Linaro, Tech Lead
Clark Boylan, clark@openstack.org, Open Infrastructure Foundation

### Project Title and description
OpenStack is an open source cloud computing infrastructure software project and is one of the three most active open source projects in the world. OpenStack is a cloud operating system that controls large pools of compute, storage, and networking resources throughout a datacenter, all managed and provisioned through APIs with common authentication mechanisms. 

Actually it is the standard for private cloud and have been widely used in many private cloud environment both on X86_64 and Arm64.

### Describe your use case for these machines
Those machines are remote involved into OpenDev Zuul nodepools, and then continue running the CI jobs defined for OpenStack on Aarch64. Those jobs are mainly covered the unit test, disk image builder, Tempest test and deployment tools, etc for OpenStack has key components, currently some test jobs are running already as listed on OpenDev CI nodepools: https://zuul.openstack.org/jobs, filling into `arm64` you will see how many jobs are running on these machines. Almostly everyday more than 20 jobs are scheduled and running for OpenStack on Arm64, so it is a quite busy CI.

Currently we use the 10 Qualcomm Centriq 2400 machines provided by Equinix Metal 3 years ago, And I think thats should be something related with previous WorksonArm project(feel free to correct me). But the Open Infra Foundation was notified that those machines are EOL and no free hardware can be replaced. So we are thinking of if we can seek Works on Arm projects for the resource help.

The cluster would be better to have 3 c3.large.arm machines, and also 1 lower performance machines server as the virtual router(This one can be either X86_64 or Arm64.)

### Which members of the community would benefit from your work?
All the Arm64 server verdors, Arm64 Edge chip vendors , the OS vendors

### Is the code that you’re going to run 100% open source? 

[OpenStack Code Repo](https://opendev.org/openstack)

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
No.

### What infrastructure (computing resources and network access) do you need?

This is a long-term CI job running. Linaro was setup the environment for Open Infra foundation OpenStack CI before, so we will continue set up and maintain the resources, keep the OpenStack CI working

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes?
Yes, definitely used by OpenDev(OpenStack CI)

Please share a public URL of the CI dashboard (if applicable).
https://zuul.openstack.org/status
In the main page, there is a individual process called "check-arm64"

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Please double check with clark@openstack.org

### Please state your contributions to the open source community and any other relevant initiatives.

Kevin Zhao is currently a Tech Lead for Linaro’s Datacenter & Cloud Group, focusing on Cloud Infra and Storage. He is serving as the Core Reviewer for OpenStack Multi-Arch SIG project and is a Maintainer for virtual-kubelet OpenStack provider. Currently he is the also the active contributor for Lustre project, to enable the Lustre server support on Arm64. 
Here is the link of my OpenStack contribution: https://review.opendev.org/q/owner:kevin.zhao%2540linaro.org
And also my Linkedin page: https://www.linkedin.com/in/kevin-zhao-shuai/

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by cboylan** [comment]
Really quickly, we don't have any problems hosting your logo on our websites to provide credit for where these resources are coming from. Use of our logos on your end would require more information on their usage before that is approved.

I would also like to expand a bit on what Kevin has already written. These resources would be used by the OpenDev Zuul CI system. OpenStack is a large and prominent user of this CI system, but all of the projects we host would have the opportunity to run ARM CI testing through this system. All of the projects we host are required to be open source and they can be browsed at https://opendev.org/.

OpenStack CI and testing serves as a great proxy for testing the broader Linux ecosystem as OpenStack depends on a number of other systems. The Linux kernel, Python, OVS, LVM, SeLinux, Ansible, Docker (and other container runtimes), MariaDB, and so on are all leveraged by OpenStack and OpenStack's integration testing. When problems are found in these tools OpenStack does its best to debug and report (and where possible, fix) these issues upstream.

OpenStack isn't the only project we host. Zuul (the CI system we run) is also hosted on OpenDev and includes subcomponents that currently rely on buildx qemu emulated arm environments for Docker image builds. There is potential here for doing tasks like this natively to improve performance as well as expanding to functional testing of the images on their native architecture.

In addition to this, we perform what we call "Third Party CI Testing" against a limited number of open source upstream dependencies for the projects we host. For example, Python Cryptography is a dependency of many modern Python code bases. Cryptography is not completely native python which requires binary installation or development dependencies at installation time. The build toolchain for Cryptography isn't trivial (includes things like Rust) which makes binary installations important. Currently we provide third party CI to Cryptography for ARM64 which they leverage to build and publish their binary Linux ARM64 packages to https://pypi.org/.

Finally, https://zuul.opendev.org/ will give you the full view of what the CI system is currently running. https://zuul.openstack.org/ only gives you an OpenStack specific view.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by ianw** [comment]
Apart from the testing of changes helping developers, the heavy workout OpenDev give these clouds is also useful.  We cycle a lot of virtual machines, upload fresh testing images daily and generally tests are fairly intensive.  We have a history of working with Linaro over a long period of time to help understand performance and stability issues that (I don't want to speak for them) have hopefully helped them managing production deployments of arm64 better.  This obviously benefits everyone :)

> Almostly everyday more than 20 jobs are scheduled and running for OpenStack on Arm64, so it is a quite busy CI.

I would add the job definitions are a good guide of how widely across OpenDev projects ARM64 testing is of interest, and what type of testing they do.  One job can be used by many projects; e.g. if you look at the one job "openstack-tox-py38-arm64" that runs tox under python3.8 

* https://zuul.openstack.org/builds?job_name=openstack-tox-py38-arm64

you can see it runs across many projects.

Each time a change is uploaded CI jobs then run, which means daily cloud resource usage is really something like (jobs defined * projects using that job * developer activity on project) -- the second and third numbers can be quite large :)  OpenDev publishes live and historic usage stats for each of our clouds e.g. for linaro feel free to explore

* https://grafana.opendev.org/d/391eb7bb3c/nodepool-linaro?orgId=1&from=now-24h&to=now

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same.

**Comment by shipra-ps** [comment]
Hi Team,

We have sent one important communication from Shipra.Snehi@arm.com . Request you to check that email and acknowledge.

Regards,
Shipra Snehi
WOA Program Team
