### ISSUE TITLE
Istio Arm CI - Works On Arm Sponsored

### ISSUE THREAD

**Issue by TrevorTaoARM** [WorksOnArm/equinix-metal-arm64-cluster#309]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Trevor Tao Trevor.Tao@arm.com
Ruquan Zhao Ruquan.Zhao@arm.com

Note that projects with two or more participants are preferred.

### Project Title and description

Istio Arm CI 
Now we want to enable the Istio Arm CI, which would enable the Istio on Arm with the needed jobs to build all images/binaries and do all the tests for arm. 
Istio is a very important service mesh infrastructure project which are widely used today. Istio extends Kubernetes to establish a programmable, application-aware network using the powerful Envoy service proxy. Working with both Kubernetes and traditional workloads, Istio brings standard, universal traffic management, telemetry, and security to complex deployments.

An official site to introduce Istio:
https://istio.io/

### Describe your use case for these machines

All Arm CI jobs would run on these arm machines.
We need to deploy a whole Kubernetes cluster on arm machines to run a Prow based CI system. All CI jobs would be run in this system, and the number of jobs are large and some of the jobs(e.g., building istio/proxy, e2e test) are very resource exhaustive.
Now Istio CI jobs are only runs on the x86_64 platform:
https://prow.istio.io/
After adding our arm resources, we can see those jobs running on arm platform too. 
It would enable Istio on arm then.

### Which members of the community would benefit from your work?
All Istio users and developers.

### Is the code that you’re going to run 100% open source? 
Yes, 100% open source

Provide the URLs where it is located, or a Git repository.
https://github.com/istio/istio

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not sure. But ARM64. 

### What infrastructure (computing resources and network access) do you need?

We need at least 2-3 powerful bare metal arm machines, e.g, Ampere Altra servers to run a lot of CI jobs which would be time and resource exhaustive.
If one of them are VM based, it should be also be enough powerful, e.g, with at least 32GB memory and more than vCPUs.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Continuous long term support is needed.

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes?

I think most probably yes, but they may be at times used by developers directly to reproduce certain bugs.

Please share a public URL of the CI dashboard (if applicable).
https://prow.istio.io/

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Not sure, please contact John Howard <howardjohn@google.com>

If No / Not Sure, Please share the relevant contact.

### Please state your contributions to the open source community and any other relevant initiatives.

https://github.com/istio/istio/pull/35011
https://github.com/istio/istio/pull/35965
https://github.com/istio/istio/pull/35994
https://github.com/istio/istio/pull/36042

https://github.com/istio/istio/issues/35176

Brag a little bit about yourself, please!

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by TrevorTaoARM** [comment]
Any progress here?

**Comment by TrevorTaoARM** [comment]
Istio arm CI is available now, thanks.
