### ISSUE TITLE
Debian ELTS (Extended Long Term Support) - Works On Arm Sponsored

### ISSUE THREAD

**Issue by sdelafond** [WorksOnArm/equinix-metal-arm64-cluster#311]
### Name, email, company, job title

Sébastien Delafond <seb@freexian.com>

https://freexian.com

### Project Title and description

ELTS program (https://deb.freexian.com/extended-lts)

This service provides security support for a subset of packages in
Debian 8 and 9: business and enterprise customers pay to select which
packages they want support for, but those resulting packages are always
made publicly available to the entire Debian community.

### Describe your use case for these machines

We'll use them as KVM hypervisors to run all the VM instances needed to
build packages for the following Debian architectures: armel, armhf and
arm64.

### Which members of the community would benefit from your work?

Debian 8 and 9 users on ARM.
The ARM community.

### Is the code that you’re going to run 100% open source? 

All the packages that we build as part of this service come directly
from Debian, and as such are fully open-source; the code can be found
here:

    http://ftp.debian.org/debian/
    https://salsa.debian.org/public

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No.

### What infrastructure (computing resources and network access) do you need?

We're mostly looking for continuous ongoing support to keep the ELTS
project up-to-date on ARM platforms.

Depending on the specs, we should be able to get by with one or two
machines: we do not have super strong performance requirements, as ELTS
only handles a subset of Debian packages, but we'll happily use the most
powerful machines you can spare for us :)

### Describe / Name the continuous integration (CI) system for this project.

We'll be using buildd/rebuildd instances in dedicated VMs.

Will these machines be exclusively used for CI purposes?

Yes.

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes.

### Please state your contributions to the open source community and any other relevant initiatives.

As individuals, we're all long-time Debian developers, involved in
various Debian teams.

As for the company itself, Freexian has been providing LTS and ELTS to
the entire Debian community for a long while now.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same
