### ISSUE TITLE
Mandrel - Works On Arm Sponsored

### ISSUE THREAD

**Issue by Karm** [WorksOnArm/equinix-metal-arm64-cluster#312]
### Name, email, company, job title

* Foivos Zakkak, zakkak@redhat.com, Red Hat, Inc., Senior Software Engineer
* Galder Zamarreno, galder@redhat.com, Red Hat, Inc., Principal Software Engineer
* Michal Karm Babacek, karm@redhat.com, Red Hat, Inc., Principal Software Quality Engineer
* Severin Gehwolf, sgehwolf@redhat.com, Red Hat, Inc., Principal Software Engineer

### Project Title and description

[Mandrel](https://github.com/graalvm/mandrel) is [a downstream distribution of the GraalVM community edition](https://developers.redhat.com/blog/2020/06/05/mandrel-a-community-distribution-of-graalvm-for-the-red-hat-build-of-quarkus/). Mandrel's main goal is to provide a native-image release specifically to support [Quarkus](https://github.com/quarkusio/quarkus). Mandrel can best be described as a distribution of a regular OpenJDK with a specially packaged GraalVM Native Image builder (native-image).

When users download our [Mandrel release](https://github.com/graalvm/mandrel/releases/), they get a full fledged JDK distribution based on [Temurin 17](https://github.com/adoptium/temurin17-binaries/releases/) and [Temurin 11](https://github.com/adoptium/temurin11-binaries/releases/), enhanced with native-image from GraalVM community edition.

Users can compile their Java applications ahead of time, creating standalone executables that do not require any JVM installation on the host system.

### Describe your use case for these machines

Mandrel project already offers [Linux ARM64 binaries](https://github.com/graalvm/mandrel/releases/), although our capability to deeply test, enhance and optimize on a modern server-class ARM hardware is limited. We would like to change that and take the efficiency of cloud-native Quarkus https://quarkus.io/ applications built with Mandrel to the next level.

### Which members of the community would benefit from your work?

* Apart from [Mandrel](https://github.com/graalvm/mandrel) user base, the broader [GraalVM Community Edition](https://github.com/oracle/graal) ecosystem would benefit from bug fixes and optimizations we achieve.
* [Quarkus](https://github.com/quarkusio/quarkus) users who use Mandrel to build their applications into standalone executables on Linux aarch64.

### Is the code that you’re going to run 100% open source? 

Yes, it is.

* Downstream distribution of the GraalVM community edition: https://github.com/graalvm/mandrel/ (in branches, e.g. 21.3, 22.2, etc.)
* Quarkus is a Cloud Native, (Linux) Container First framework for writing Java applications: https://github.com/quarkusio/quarkus

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No, although we would like to explore the possibility.

### What infrastructure (computing resources and network access) do you need?

We would like to gain access to IaaS-style, bare metal resources, two dedicated systems.
This is a long-term, ongoing effort as the low-hanging fruit is already gone, i.e. Mandrel compiles and  runs on aarch64.

### Describe / Name the continuous integration (CI) system for this project.

Publicly accessible Jenkins.

Will these machines be exclusively used for CI purposes?

No. CI would be a majority of the workload though. We will also use them for hands-on investigations and profiling.

Please share a public URL of the CI dashboard (if applicable).

https://ci.modcluster.io/view/Mandrel/job/mandrel-jobs/

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes.

### Please state your contributions to the open source community and any other relevant initiatives.

We are a group of programmers with backgrounds spanning OpenJDK, compiler engineering, large distributed systems, clustering, and loadbalaning. Notable relevant projects:

 * https://github.com/adoptium/jdk
 * https://github.com/quarkusio/quarkus
 * https://github.com/oracle/graal
 * https://github.com/graalvm/mandrel/
 * https://github.com/infinispan/infinispan

## Important reminders and logistics

> Approved projects will be expected to provide credit back to Works on Arm
> in the form of a logo display, blog post, Twitter post, news release, or
> some other suitable acknowledgement.

We will be glad to do that.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by pgmwoa** [comment]
Ticket resolved hence closing the same.
