### ISSUE TITLE
RebornOS ARM - Works On Arm Sponsored

### ISSUE THREAD

**Issue by Rippanda12** [WorksOnArm/equinix-metal-arm64-cluster#313]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

- Panda hi@liketraps.com RebornOS, Developer for arm
- CookieSource team@rebornos.org RebornOS, Project lead

Note that projects with two or more participants are preferred.

### Project Title and description

https://rebornos.org/

RebornOS ARM - RebornOS ARM is an archlinux based distribution that has flagship apps and features

### Describe your use case for these machines

Build packages/OSS binaries/Develop RebornOS for arm based machines

### Which members of the community would benefit from your work?

Any SBC users like pi, odroid, rock, quartz and more.

### Is the code that you’re going to run 100% open source? 

Yep it can all be found https://github.com/RebornOS-Developers and my profile

Provide the URLs where it is located, or a Git repository.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
not sure

### What infrastructure (computing resources and network access) do you need?

Probably any arm64 8gb ram/6-8C cpu with nested virtualization if possible

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes?

Probably after we develop our panel

Please share a public URL of the CI dashboard (if applicable).

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes ofcource.
If No / Not Sure, Please share the relevant contact.

### Please state your contributions to the open source community and any other relevant initiatives.

Features that aren't present on Manjaro arm/Archlinux ARM like downgrade utility for downgrading packages support for 12 desktop enviroments i also try to maintain as much hardware as possible

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by Rippanda12** [comment]
Any updates?

**Comment by pgmwoa** [comment]
Sorry for delay, we are still looking in to it.

**Comment by Rippanda12** [comment]
I would like to ask if you have any ARMv8.**3** machines since i want to use nested virtualization

**Comment by vielmetti** [comment]
There is a table here

https://marcin.juszkiewicz.com.pl/download/tables/arm-socs.html

of processor features. If you know precisely which features you need from the CPU, you can look them up there.

The Ampere Altra here is advertised as "ArmV8.2+", and I don't know if the + includes the features you request.

**Comment by pgmwoa** [comment]
Closing the GitHub ticket for now, as discussed in the email. You could recheck with us again after 3 months and reopen the ticket as required with latest information.
