### ISSUE TITLE
python-lz4 - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jonathanunderwood** [WorksOnArm/equinix-metal-arm64-cluster#315]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Jonathan Underwood. jonathan.underwood@gmail.com.

### Project Title and description
[python-lz4](https://github.com/python-lz4/python-lz4) - python bindings for the LZ4 compression package.

### Describe your use case for these machines
This project provides pre-compiled Python wheels via PyPi, built using github actions. At present we don't ship Aarch64 wheels due to github actions not supporting Aarch64 builds.

### Which members of the community would benefit from your work?
Python-lz4 is a dependency of hundreds of Python packages.

### Is the code that you’re going to run 100% open source? 
Yes.

Provide the URLs where it is located, or a Git repository.
https://github.com/python-lz4/python-lz4

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not sure.

### What infrastructure (computing resources and network access) do you need?
Aarch 64 machines for CI/CD. Even better would be shell access for development and testing.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.
Continuous

### Describe / Name the continuous integration (CI) system for this project.
Github actions.

Will these machines be exclusively used for CI purposes?
Yes.

Please share a public URL of the CI dashboard (if applicable).
https://github.com/python-lz4/python-lz4/actions

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure
Not sure - we don't currently have a logo!

If No / Not Sure, Please share the relevant contact.
I am the contact.

### Please state your contributions to the open source community and any other relevant initiatives.
Python-lz4 maintainer, contributor to Fedora and OpenWrt.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by martin-g** [comment]
@jonathanunderwood have you considered using QEMU emulation ?
It is easy to set it up on Github Actions with `uraimo/run-on-arch-action` action.
You can see how I did it for Ninja build tool [here](https://github.com/ninja-build/ninja/blob/089927e0a7082887304a8d8ed8c122e8615d9cf1/.github/workflows/linux.yml#L151-L191)

The drawback is that it will be slower than on native environment, but I doubt this will be a problem for your project.

With self-hosted runner on a public repository you will have to be careful not to use it for Pull Requests. See https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security
It will be OK if you use it only in a workflow that is executed on `push` to a tag (release) though.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by pgmwoa** [comment]
Closing the GitHub ticket for now, as discussed in the email. Ticket can be reopened anytime with latest information and we will take it forward.
