### ISSUE TITLE
Velero - Works On Arm Sponsored

### ISSUE THREAD

**Issue by danfengliu** [WorksOnArm/equinix-metal-arm64-cluster#316]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
danfengl@vmware.com
Vmware

Note that projects with two or more participants are preferred.

### Project Title and description
Velero
Back up and restore your Kubernetes cluster resources and persistent volumes

### Describe your use case for these machines
Some of Velero E2E tests, not all of them.
 
### Is the code that you’re going to run 100% open source? 
Yes

Provide the URLs where it is located, or a Git repository.
https://github.com/vmware-tanzu/velero

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not Sure

### What infrastructure (computing resources and network access) do you need?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.
Git action

Will these machines be exclusively used for CI purposes?
Yes

Please share a public URL of the CI dashboard (if applicable).

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure
Yes

If No / Not Sure, Please share the relevant contact.

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by danfengliu** [comment]
Sorry for the late response. We like to run Velero E2E test on Arm platform, as per [Velero E2E git action](https://github.com/vmware-tanzu/velero/blob/main/.github/workflows/e2e-test-kind.yaml) , our tests will not cost too much storage, ubuntu will be deployed and then golang and docker are essential developing tools on it. Currently one VM is OK for us. Should I still provide the specific number of cores and memory?

**Comment by pgmwoa** [comment]
Closing the GitHub ticket for now, as discussed in the email. You could recheck with us again and reopen the ticket as required with latest information.
