### ISSUE TITLE
Anouki, Gameserver Hosting - Works On Arm Sponsored

### ISSUE THREAD

**Issue by Knight1** [WorksOnArm/equinix-metal-arm64-cluster#317]
### Name, email, company, job title

Tobias Sachs, known, not applicable, Student

### Project Title and description

Anouki, Hosting of (free) Game (Minecraft) Servers on ARM <3

I had the Idea of hosting minutly billed gameservers with Packet.net back in the days when i got invited to the arm hacking group in the packet.net Slack via hourly rented servers. So the customer only pays when they actually use the server. But that sadly never happend due to a very limited amount of available servers, glitches in Minecraft, limited disk space and my available time. Now i would like to give it another shot via reserved instances. Minecraft no longer have weird graphical glitches and the Client even supports Apple Silicon, Pterodactyl supports arm64, the new Servers are having a much better single Core performance then before which is great for Minecraft. The long term Idea is still to only utilise the gameserver ressources only when there are Players playing. This saves money for the user and operational costs. 

On the other hand sponsored Minecraft Servers with hosted on ARM Sponsoring Logo would be a great effort and push too imho.

### Describe your use case for these machines

Services:
    - Minecraft
    - Other Games called 'eggs' - if arm64 is supported
    - Databases
    - Storage

Own Infrastructure:
    - Website / Webinterface
    - API / Bots
    - CI Pipeline
    - Helpsystem, Mails

### Which members of the community would benefit from your work?

Minecraft Community. I would like to prove that arm64 is a great platform even for gameservers. Now that Apple made the move and my Macbook Pro is a great daily driver I am more thrilled then ever. 

### Is the code that you’re going to run 100% open source? 

[Webinterface](https://github.com/pterodactyl)
I am not a developer i just use it and love it like everyone else.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

We need "c3.large.arm64" due to the nature that Minecraft is heavily single Threaded and memory hungry. 

### What infrastructure (computing resources and network access) do you need?

This is a long time support Idea if it runs well. Servers would be paid by Customers or by Ads in the long run. Fixed IP Addresses / reserved instances would be appreciated in a stages if the project runs well. 

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes? => No.

Please share a public URL of the CI dashboard (if applicable). => not applicable

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

No logo, yet.

### Please state your contributions to the open source community and any other relevant initiatives.

https://tobiassachs.de/2017/01/22/90-Minecraft-Server-auf-ARMv8-ThunderX.html

https://github.com/robbertkl/docker-ipv6nat/issues/9
https://github.com/docker-library/official-images/issues/2550
https://github.com/hashicorp/packer/issues/4886
https://github.com/hashicorp/consul/issues/3042
https://github.com/hashicorp/nomad/issues/2643

Sadly the Packet Slack Channel with the arm Hacking Project was archived ;(

I remember one or two Mentionings on the Packet.net Newsletter.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm in the form of a logo display, blog post, Twitter post, news release, or some other suitable acknowledgement.

If there is a Hosted On Arm Logo I would gladly put it on the Website / Discord.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by pgmwoa** [comment]
Please share your email id.

**Comment by Knight1** [comment]
Hi pgmwoa! 👋 

You can send an email to firstname at (project title) dot de 😇

**Comment by pgmwoa** [comment]
> Hi pgmwoa! 👋
> 
> You can send an email to firstname at (project title) dot de 😇

Kindly check email dated 25th Jan 2023, send on 'tobias@anouki.de' .. hope we got it right :-)

**Comment by pgmwoa** [comment]
Closing the GitHub ticket for now, as discussed in the email. You could recheck with us again after 3 months and reopen the ticket as required with latest information.
