### ISSUE TITLE
GNU toolchain linaro builds - Works On Arm Sponsored

### ISSUE THREAD

**Issue by giabusarm** [WorksOnArm/equinix-metal-arm64-cluster#319]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Vidya Praveen, vidyapraveen@arm.com, arm, Senior Engineering Manager, GNU Tools
Gianluca Busiello, gianluca.busiello@arm.com, arm, Staff DevOps Engineer
Maxim Kuvyrkov, maxim.kuvyrkov@linaro.org, linaro, Toolchain Tech Lead at Linaro

### Project Title and description

Linaro infrastructure for GNU toolchain arm builds

### Describe your use case for these machines

We require Linaro to build and test the GNU toolchain for all arm variants so that regressions introduced for our architecture are quickly identified and the author is notified accordingly.

### Which members of the community would benefit from your work?

Any application based arm running linux, android and MacOS(applesilicon) benefits from the GNU toolchain.

### Is the code that you’re going to run 100% open source? 

Yes, these are very well known opensource projects:
GCC, Binutils, Glibc, GDB, Newlib

### What infrastructure (computing resources and network access) do you need?

We need 2 x Ampere Altra dual socket (160 cores, 512GB RAM, 2TB NVMe U.2 SSD)
We can start with the allocation of 1 node in the short term, and, at the first review, evaluate the possibility to scale up the load on a second machine.
The allocation needs to be permanent.

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes? 
Yes, in Linaro they are already using a similar setup in Jenkins to build the gnu toolchain for a limited number of arm profiles but, in order to build all the variants that we need, for all profiles (A, R, M), they need to add more compute resources to their jenkins infrastructure.

Please share a public URL of the CI dashboard (if applicable).
https://ci.linaro.org/

### Does the project allows the use of your project logo on ARM's developer website freely? Not Sure

If No / Not Sure, Please share the relevant contact.

Maxim Kuvyrkov, maxim.kuvyrkov@linaro.org, linaro, Toolchain Tech Lead at Linaro

### Please state your contributions to the open source community and any other relevant initiatives.

The GNU Toolchain powers all linux distributions in the world (they are essentially built using our toolchain and glibc forms the core of the user space / runtime).
GNU Tools team in arm is responsible for enabling Arm Architectures and CPUs in GNU Toolchain which is composed primarily of 5 very large open source projects (GCC, Binutils, Glibc, GDB, Newlib). All our work is committed upstream in to these projects' public repositories. 
There are hundreds of patches committed on a daily basis by people from all over the world to these projects and it is important to make sure that we ensure their commits are not breaking our ports (aarch64 and arm). We have been internally heavy lifting this for a long time but it has come to a point we cannot scale this up. We need to automate this process and automatically chase the authors quickly when something fails (so that they fix it immediately). We realised Linaro already has a system that can do this mostly. And we share exactly the same objectives - to ensure quality of the Arm ports. 

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Request is being processed and you will receive an email notification on the same.

**Comment by pgmwoa** [comment]
This request is been fulfilled under the project "Linaro - GNU toolchain - Works On Arm Sponsored" #234
