### ISSUE TITLE
CPython public benchmark machine

### ISSUE THREAD

**Issue by diegorusso** [WorksOnArm/equinix-metal-arm64-cluster#322]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Diego Russo, diego.russo@arm.com, Arm Ltd, Principal Software Engineer
Rodolph Perfetta, rodolph.perfetta@arm.com, Arm Ltd, Distinguished Engineer

### Project Title and description

CPython public benchmarking.

In order to have a full integration of aarch64 benchmarks in speed.python.org, we've been asked to provide a public working prototype of such infrastructure. For more info please refer to this discussion: https://discuss.python.org/t/about-speed-python-org-and-aarch64/22519

### Describe your use case for these machines

Initially the machine will be running the server for displaying the benchmark results  and based on the community response the machine could be repurposed to run benchmarks.

### Which members of the community would benefit from your work?

The CPython community targeting aarch64.

### Is the code that you’re going to run 100% open source? 

Yes.
Codespeed: https://github.com/tobami/codespeed
Pyperformance: https://github.com/python/pyperformance

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No.

### What infrastructure (computing resources and network access) do you need?

Standard network access will suffice.
Minimal compute resources: 16 cores, 64GB Ram, 200GB storage.
Initially short-term support and depending the community response we could consider long term support.

### Describe / Name the continuous integration (CI) system for this project.

We intend to replicate speed.python.org and it is a way to convince the community to have aarch64 benchmarks.

Will these machines be exclusively used for CI purposes?

Initially no but depending on the community response they could run recurrent/daily benchmarks.

Please share a public URL of the CI dashboard (if applicable).

speed.python.org

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

No.

If No / Not Sure, Please share the relevant contact.

psf-trademarks@python.org

### Please state your contributions to the open source community and any other relevant initiatives.

I gave a talk at EuroPython 2023, "Python on Arm". Recording can be found here: https://www.youtube.com/watch?v=C2UpwjcN4cw&t=4528s

As part of the work I'm doing, we have an ongoing engagement with the CPython community to provide an infrastructure for aarch64 benchmark metrics (please refer to the discussion at the top of the issue). After a few discussions I had with CPython core developers during the conference, there is desire to move this matter forward.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by shipra-ps** [comment]
Ticket resolved hence closing the same.
