### ISSUE TITLE
Ultramarine Linux, Terra, Fyra Labs - Works On Arm Sponsored

### ISSUE THREAD

**Issue by lleyton** [WorksOnArm/equinix-metal-arm64-cluster#323]
### Name, email, company, job title

Lleyton Gray, lleyton@fyralabs.com, Fyra Labs, Founder/CEO

### Project Title and description

There are several projects we’re applying for, but they’re all related and support each other:

- Ultramarine Linux is a Fedora-based Linux distribution designed for ease-of-use, regardless of experience and use-case.

- Terra is a rolling-release community repository for Fedora containing a variety of software, with desktop users in mind.

- Ultramarine Anywhere is a project to bring Ultramarine (and Linux as a whole) to as many people as possible. We achieve this by working on hardware support for “non-traditional” platforms. Our major focus at the moment is working alongside the Chultrabook project to allow Ultramarine to seamlessly run and function on Chromebook hardware, especially ARM devices.

- Fyra Labs software (all open-source) as a whole, as we'd like to offer ARM builds :p

### Describe your use case for these machines

We mainly want to use these machines as CI for aarch64 packages in Terra ARM. We also would like to be able to use them for development builds, outside of the CI environment. (ex. our patched builds of the kernel with hardware support patches)

### Which members of the community would benefit from your work?

Everyone who uses Ultramarine Linux on ARM. This would also benefit the users of Terra, which are spread across the Fedora ecosystem, outside of just Ultramarine. Additionally, our work on hardware support would be able to benefit those who are on the platforms we’re developing for, across the Linux ecosystem.

### Is the code that you’re going to run 100% open source? 

Yes, all of the code we're using is open source. However, certain packages in Terra may be for 3rd party proprietary software, for example, we provide a package for Discord desktop.

https://github.com/terrapkg/packages
https://github.com/ultramarine-linux/ (the entire org is relevant)
https://github.com/FyraLabs/kaibutsu (our patches and build system for kernel development and testing)
https://github.com/ellyq/linux (development tree for mt8183 kernel patches, from the chultrabook project, used in Ultramarine)

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Unsure, but preferred.

### What infrastructure (computing resources and network access) do you need?

We’re looking for continuous support as we push new packages, requiring new builds.

Specs wise, we would want networking, with full-access to the machines so we may configure them for our needs. One or two (or three) of the Ampere Altra machines should suffice, but we’ll happily take more powerful (or more) machines if it can be spared. ;3

### Describe / Name the continuous integration (CI) system for this project.

We primarily use GitHub Actions for CI.

Will these machines be exclusively used for CI purposes?

No, we also want to be able to execute builds outside of CI for development builds.

Please share a public URL of the CI dashboard (if applicable).

CI runs can be viewed at the /actions page of each repo.

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes. We're okay with ARM's developer website using both the Ultramarine Linux and Fyra Labs logo, as long as in good faith.

### Please state your contributions to the open source community and any other relevant initiatives.

I’ve personally been working on open source for years now, initially starting in the web/frontend space, moving more into Linux (ex. GNOME, xdg-portals, etc.) Our projects, Ultramarine Linux and Terra have bolstered the Fedora ecosystem, paving a way for newcomers to more easily start with Linux and access the software they need. Our company, Fyra Labs was founded exclusively to develop and maintain open source products, in order to prove that fully libre software can both be commercially viable and sustainable, as well as, a better alternative to proprietary software products.

## Important reminders and logistics

Thank you all so much :3

**Comment by lleyton** [comment]
Heya, thanks for approving this! When do you think the resources will be ready?

**Comment by shipra-ps** [comment]
Have you got any welcome email from Equinix? Pls confirm

**Comment by lleyton** [comment]
Yup, we just got it! Thank you so much.
