### ISSUE TITLE
GOALS - Works On Arm Sponsored

### ISSUE THREAD

**Issue by torbjornsoderman** [WorksOnArm/equinix-metal-arm64-cluster#324]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Torbjörn Söderman, torbjorn@playgoals.com, GOALS AB, Technical Director
Jonas Rundberg, jonas@playgoals.com, GOALS AB, CTO
Tim Johansson, tim@playgoals.com, GOALS AB, Principal Engineer
Anders Roos, anders@playgoals.com, GOALS AB, Backend Engineer
Johan Mjönäs, johan@playgoals.com, GOALS AB, Cloud Infrastructure Engineer
Mikael Bergemalm, [mikael.b@playgoals.com](mailto:mikael.b@playgoals.com), GOALS AB, Cloud Infrastructure Engineer

### Project Title and description
GOALS - A free to play football game focused on the e-sport crowd. A big focus is on low latency and fast response and for this reason we are using dedicated game servers even on 1v1 game modes (11 vs 11). To become cost effective we need to run a lot of servers on a single core and we believe Arm can be a crucial partner to lower our cost compared to running on X86 based HW. In order to run efficiently on Arm server HW we need to optimize for this target and the only way to do that efficiently is to have access to HW.

### Describe your use case for these machines
We intend to use these machines to optimize our dedicated game server to work very well on Arm HW.

### Which members of the community would benefit from your work?
Our work would showcase the ability to run high performance game servers using Arm HW. We would be able to provide best practices for others game creators that would be interested in creating high performance game servers on Arm

### Is the code that you’re going to run 100% open source? 
The game server code and cloud infra code will be proprietary, but we intend to share learnings and media on how we benefit from running on Arm HW.

Provide the URLs where it is located, or a Git repository.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not Sure

### What infrastructure (computing resources and network access) do you need?
Hardware and Network connectivity that lets us run our game servers and cloud infrastructure related to fleet management, as well as network connectivity to let an external client connect to the game server.

### Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.
Most likely medium length, we need support to get our game servers and cloud infra for fleet management running and then also we need to be able to profile and optimize the game on the Arm HW.

### Describe / Name the continuous integration (CI) system for this project.
Game server uses Epic Games proprietary Horde CI system
Cloud uses Github actions and GitOps operators

Will these machines be exclusively used for CI purposes?
No

Please share a public URL of the CI dashboard (if applicable).

### Does the project allow the use of your project logo on ARM's developer website freely? Yes / No / Not Sure
Yes

If No / Not Sure, Please share the relevant contact.

### Please state your contributions to the open source community and any other relevant initiatives.

The way we see it from a benefit from your point of view would be to push the visibility of games running Arm hardware on game servers and doing this very efficiently to get both player experience benefits as well as from a cost perspective.
As you know we are making a football game, a tough market, but also there is basically only one competitor (EAFC) and if we can be a real competitor to EA in this genre we would generate a lot of buzz and hopefully a very large player base.

To be competitive we are focusing hard on creating a player first low latency football game that is focused on the tough e-sport crowd. If they like it many more will like it, is our thesis.
In order to do this we are embarking on something very few games have done for so few players. We are creating dedicated servers for 1v1, which means we need to be able to stack many game servers on one core to be cost effective, running these on Arm HW makes it also even more cost effective.
We have rewritten our UE5 OOP gameplay simulation to a custom DOD simulation engine that we intend to run standalone on the game servers to maximize the performance of the game servers and be able to run many game servers on one core.

I think there is a story to be told around this and the collaboration we can do to get this game running extremely well on ARM HW, we want to talk about it in our marketing (focus on performance and low latency is key to our target demographic) and I think it could be a marketing beat for you as well to spin on as well. 

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by shipra-ps** [comment]
Your Works on Arm program request is approved, and the necessary infrastructure is reserved on Equinix for your “GOALS” project.

Please check your email from Shipra.Snehi@arm.com and acknowledge.
