### ISSUE TITLE
Faster CPython benchmark machine

### ISSUE THREAD

**Issue by diegorusso** [WorksOnArm/equinix-metal-arm64-cluster#325]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Diego Russo, [diego.russo@arm.com](mailto:diego.russo@arm.com), Arm Ltd, Principal Software Engineer
Rodolph Perfetta, [rodolph.perfetta@arm.com](mailto:rodolph.perfetta@arm.com), Arm Ltd, Distinguished Engineer

### Project Title and description

Faster CPython public benchmarking.

In order to help the faster CPython team at Microsoft, a bare metal AArch64 machine is needed to run benchmarks on this platform.

### Describe your use case for these machines

This is related to the discussion we've had here: https://github.com/faster-cpython/benchmarking-public/issues/33
Basically the need is for a bare metal machine to support their effort in improving CPython on AArch64 (potentially targeting normal and JIT builds as well)

### Which members of the community would benefit from your work?

The CPython community targeting AArch64.

### Is the code that you’re going to run 100% open source? 

Yes.
The code is all here: https://github.com/faster-cpython/benchmarking-public

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No.

### What infrastructure (computing resources and network access) do you need?

The same specs of the machine given for https://github.com/WorksOnArm/equinix-metal-arm64-cluster/issues/322 would be enough.
This is a request for an ongoing support and re-evaluate it in the mid-term (towards the end of the year) to see if it is still needed or it can be supported via other means.

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes?

Yes, these machine will be used as CI agents in GitHub Actions for the project above (which is fully controlled by the Faster CPython team)
Occasionally it will accessed by the Faster CPython team for debugging.

Please share a public URL of the CI dashboard: https://github.com/faster-cpython/benchmarking-public

### Does the project allow the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Not sure: [trademarks@microsoft.com](mailto:trademarks@microsoft.com).

### Please state your contributions to the open source community and any other relevant initiatives.

We've already used an Equinix machine to power AArch64 benchmarks on speed.python.org and I'm engaging with the CPython community to improve CPython support on AArch64.
Moreover the Faster CPython team at Microsoft are doing an excellent job in improving performance on CPython and it is critical for the project to measure the performance on the main platforms (Tier-1 and Tier-2 platforms).

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by shipra-ps** [comment]
1 additional Mt. Snow has been reserved for the "CPython public benchmarking - Works On Arm Sponsored" project. You may deploy this new reserved server any time.
