### ISSUE TITLE
Kata Containers - Works On Arm Sponsored

### ISSUE THREAD

**Issue by ildikov** [WorksOnArm/equinix-metal-arm64-cluster#326]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Ildiko Vancsa, ildiko@openinfra.dev, Open Infrastructure Foundation, Director of Community, Kata Containers Community Manager
Anastassios Nanos, ananos@nubificus.co.uk, Nubificus LTD, Kata Containers Architecture Committee member

### Project Title and description

Kata Containers

Kata Containers is an open source, secure container runtime, building lightweight virtual machines that seamlessly plug into the containers ecosystem. The project is available under the Apache 2.0 license and is supported by the Open Infrastructure Foundation.

### Describe your use case for these machines

Use them as part of our CI, based on Github Actions. We would like to test releases and Pull Requests for the whole stack (both runtimes, go and rust), for all hypervisors that are supported on the aarch64 architecture (qemu, Cloud-hypervisor, Firecracker, Dragonball, etc.).

### Which members of the community would benefit from your work?

The whole ecosystem around Kata Containers will benefit from the ability of continuously testing the project on Arm HW, which includes users and developers alike. Anyone who has an application that needs an OCI-compatible container runtime solution that supports isolation, and with that supports data security, multi tenancy, etc, benefits from Kata Containers. While the community has users participating in the project, the ability to test the code on diverse HW architectures, while under development, makes the solution much more stable, robust and reliable.

### Is the code that you’re going to run 100% open source? 

Yes, the code is available on GitHub: https://github.com/kata-containers/kata-containers

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No

#### Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

The Kata Containers community needs 3-5x Ampere Altra systems. We can start with the allocation of 3 systems in the short term and at the first review, evaluate the possibility to scale up the load on more machines.

The community is looking for long-term, continuous ongoing support.

### Describe / Name the continuous integration (CI) system for this project.

Github Actions

#### Will these machines be exclusively used for CI purposes?

Yes

#### Please share a public URL of the CI dashboard (if applicable).

Not a dashboard, but it shows tests that the community would like to run on ARMv8 machines: https://github.com/kata-containers/kata-containers/actions/runs/9051451418 

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes, please contact Wes Wilson ([wes@openinfra.dev](mailto:wes@openinfra.dev)) for next steps

### Please state your contributions to the open source community and any other relevant initiatives.

The Kata Containers open source project, supported by the Open Infrastructure Foundation, was launched in 2017, and currently has a global, very diverse community who works on evolving and maintaining the solution. The project has frequent minor releases to ensure fast progress and accessibility to new improvements fast.

The project has been used in production for years, where it is running on large scale to power use cases such as payment systems, regulated environments like healthcare and telecommunications, AI/ML and more. While the community has users participating in the project, the ability to test the code on diverse HW architectures, while under development, makes the solution much more stable, robust and reliable. Companies such as Ant Group, Alibaba Group, IBM, Intel and NVIDIA are among the project's users and contributors. The project has a continuously running user survey, where 40% respondents over the past one year indicated that they are running the project in production, both in public and private clouds, and another 40% is currently evaluating Kata Containers.

You can find more information about Kata Containers users and use cases on the project's website: https://katacontainers.io/use-cases/ 

The growing interest in the project is also shown by the 57.5% increase in web traffic year over year on  katacontainers.io between 2022 and 2023.

Kata containers have been laying the foundation for a number of commercial offerings, related to container sandboxing and confidential container offerings from companies like Microsoft, Redhat, Huawei etc. Some of the end-products that are based on kata-containers can be found below:
- https://techcommunity.microsoft.com/t5/apps-on-azure-blog/preview-support-for-kata-vm-isolated-containers-on-aks-for-pod/ba-p/3751557
- https://techcommunity.microsoft.com/t5/azure-confidential-computing/aligning-with-kata-confidential-containers-to-achieve-zero-trust/ba-p/3797876
- https://www.redhat.com/en/blog/learn-openshift-sandboxed-containers
- https://www.alibabacloud.com/blog/getting-started-with-kubernetes-%7C-secure-container-technology-from-the-founder-of-kata-containers_596340
- https://support.huaweicloud.com/intl/en-us/cci_faq/cci_faq_0009.html

Additionally, AWS recently featured a blog post, describing how to setup kata-containers on AWS EKS: https://aws.amazon.com/fr/blogs/containers/enhancing-kubernetes-workload-isolation-and-security-using-kata-containers/ 

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by ildikov** [comment]
@bhumikpatel @shipra-ps 

Hi, I'm reaching out to follow up on this issue that I created on behalf of the Kata Containers open source community.

I haven't seen or received any communication regarding evaluating our application to participate in the Works On Arm program. The community is still in need for Arm resources and we hope to be able to participate in the program.

Are there any additional information that you need or any steps we need to take to move the application forward?

Thanks and Best Regards,
Ildikó

**Comment by shipra-ps** [comment]
Hi @ildikov ,

We are in the process of reviewing your request. Kindly allow us sometime to get back.

Regards,
Shipra Snehi

**Comment by shipra-ps** [comment]
Hi @ildikov ,

Kevin Zhao must have had reached out to you and clarified that we already have 3 x.large.arm machines reserved for the Kata-container community since almost 3 years. Hope your requirement is also covered in that and I can now proceed with closing the ticket.

**Comment by ildikov** [comment]
@shipra-ps Thank you for getting back to me. I looked it up, and Kevin Zhao did chime in on one conversation on the Kata Slack, which was related to ARM HW for CI testing. He did not reach out to me or Anastassios directly. Do you happen to have any information about who from the Kata community arranged the access to the 3 machines you're referring to?

Kevin did not clarify whether the machines he has access to are related to this program or not. He was also talking about 2 machines and not three.

I will still need to confirm with the community whether all their CI needs are currently met, based on the recently uncovered information. Please allow me a little time for that.

Before we close this issue, I would like to sort out the details of Kata's participation in the Works on Arm program and make sure that it is administered correctly on both ends:

- Can you please confirm that the 3 x.large.arm machines you mentioned are allocated to the Kata Containers project through the 'Works on Arm' program?
- Can you please add Anastassios and I as contact persons for the Kata Community?
    * Ildiko Vancsa, [ildiko@openinfra.dev](mailto:ildiko@openinfra.dev), Open Infrastructure Foundation, Director of Community, Kata Containers Community Manager
    * Anastassios Nanos, [ananos@nubificus.co.uk](mailto:ananos@nubificus.co.uk), Nubificus LTD, Kata Containers Architecture Committee member
- Is Kevin Zhao the contact person for the 'Works on Arm' program on your end? Or that someone else?

Thanks,
Ildikó

**Comment by kevinzs2048** [comment]
@ildikov @shipra-ps Looks that we are on the same page now, I will serve as the contact for Kata community on Arm64 CI and help to maintain the CI issue on Arm64. Just as @shipra-ps said, those 3 machines are not newly offered to upstream, they are already there for about 3 years. Previously two of them are in Kata Jenkins, and they other one for development and test.
During the last 2 days I synced with Steve Horsman from Kata CI team, already configured and added 2 machines back to GHA for Kata Arm64 CI. The other one machines is used for Kata Arm64 development and bugfix, and let's see if the CI job is intense, we can add the third machines to Kata CI as a builder to offload the CI works. That's the all status now, please feel free to let me know if any questions.

**Comment by ildikov** [comment]
@kevinzs2048 Thank you for adding the summary of our Slack conversation to this issue.

@shipra-ps I think we sorted everything out with this for now, and can close this ticket. Please keep me and Anastassios updated if there are any changes or concerns with the machines that the Kata community is using.

Thank you both for the help!

**Comment by shipra-ps** [comment]
Thanks @kevinzs2048 for syncing up with @ildikov.

@ildikov , I will add you and Anastassios as collaborators to the Kata container project under Works on Arm program. You should receive the invite today.

**Comment by ildikov** [comment]
@shipra-ps Thank you! I received your email, will look out for the email from Equinix as well.

**Comment by shipra-ps** [comment]
Thankyou for the update. I am now closing this issue.
