### ISSUE TITLE
Elastic Translations - Artifact Evaluation

### ISSUE THREAD

**Issue by psomas** [WorksOnArm/equinix-metal-arm64-cluster#327]
### Name, email, company, job title

 * [Stratos Psomadakis](https://psomas.xyz), psomas@cslab.ece.ntua.gr, [Computing Systems Lab (CSLab)](https://newsite.cslab.ece.ntua.gr/people/), School of Electrical and Computer Engineering, National Technical University of Athens, PhD student
 * [Georgios Goumas](http://www.cslab.ece.ntua.gr/~goumas/), Computing Systems Lab, School of Electrical and Computer Engineering, National Technical University of Athens, Associate Professor
 * Nectarios Koziris, Computing Systems Lab, School of Electrical and Computer Engineering, National Technical University of Athens, Professor

### Project Title and description

CSLab is a member of the [AERO](https://aero-project.eu/) project consortium. In the context of AERO, we developed Elastic Translations as an extension to the Linux kernel memory manager to take advantage of ARMv8-A contiguous bit, in order to alleviate address translation overheads. Elastic Translations will be presented at the 57th IEEE/ACM International Symposium on Microarchitecture ([MICRO2024](https://microarch.org/micro57/)), which will take place between 2nd and 6th of November at Austin, Texas. We intend to integrate Elastic Translations with the rest of the AERO software ecosystem for the ARM-based [Rhea European processor](https://www.european-processor-initiative.eu/).

### Describe your use case for these machines

We developed and evaluated Elastic Translations on an Ampere Altra Mt.Jade server, hosted at our lab. We've also verified it works on an NVIDIA GraceHopper server.  We intend to make Elastic Translations publicly available (on Github), under an open source license (GPLv2) and submit it for [artifact evaluation at MICRO2024](https://ctuning.org/ae/micro2024.html). We would like to have access to another baremetal Ampere (preferably) ARM server so that the artifact reviewers will have access to a thirdparty ARM server in order to evaluate our artifact.

### Which members of the community would benefit from your work?

We hope that making our artifact available and submitting it for review at MICRO2024 AE, it will be of benefit to both the research and the opensource (Linux) communities.

### Is the code that you’re going to run 100% open source? 

Yes. The kernel part of Elastic Translations is licensed under GPLv2 (same as the Linux kernel). We publish the userspace components of ET under GPLv2 as well.

https://github.com/cslab-ntua/elastic-translations-MICRO2024

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Yes. For Elastic Translations we also leverage the Statistical Profiling Extension introduced ARMv8.2-A, in order to sample TLB misses and drive our in-kernel ET mechanism.

### What infrastructure (computing resources and network access) do you need?

One baremetal ARMv8.2+ server (preferably Ampere Altra), with at least 192GiB of memory. No specific requirements with regard to storage and networking.

The server would be required for the duration of the MICRO2024 artifact evaluation process, which starts 11th of August and ends 8th of September 2024.

### Does the project allow the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes.

### Please state your contributions to the open source community and any other relevant initiatives.

We intend to engage with the Linux kernel community and developers to discuss the possibility of upstreaming Elastic Translations and integrating it with the recent Linux mTHP (multi-sized THP) and transparent contpte features.

We are also contributing to various open-source projects, mainly in the context of EU research projects we're part of ([AERO](https://aero-project.eu/), [Daphne ](https://github.com/daphne-eu/daphne)). We've also made research artifacts available on [Github](https://github.com/cslab-ntua) under open-source licenses.

**Comment by shipra-ps** [comment]
Thanks for your interest in WoA. We will review the request and get back to you.

**Comment by shipra-ps** [comment]
Closing the GitHub ticket for now, as discussed in the email.
