### ISSUE TITLE
Helium LLC - Hydrogen - Works On Arm Sponsored

### ISSUE THREAD

**Issue by embedvr** [WorksOnArm/equinix-metal-arm64-cluster#328]
### Name, email, company, job title

Addison LeClair, addison@helium.email, Helium LLC, Founder

### Project Title and description
Helium LLC is heavily involved in development of software for the Spotify Car Thing, an ARM64 based device. This device was officially discontinued by Spotify and they claim it will cease functioning on [December 9th, 2024](https://support.spotify.com/us/article/car-thing-discontinued/).

Helium LLC's goal is to continue support for the Spotify Car Thing past December using our own operating system called Hydrogen, designed specifically for the Spotify Car Thing with help from community members. 

### Describe your use case for these machines

Due to the Spotify Car Thing being Linux-based (specifically, Buildroot), we would use these machines to compile software and packages for the device to keep the system up-to-date.

Along with attempts to update the official Spotify Car Thing operating system, we plan to use the machines to build packages for Hydrogen and to build Hydrogen itself.

### Which members of the community would benefit from your work?
All Spotify Car Thing users would benefit from our work, since it will cease operation on December 9th, 2024. We are working to keep it operational past that time.

### Is the code that you’re going to run 100% open source? 

Helium LLC's work on the Car Thing is fully open source and can be viewed from the following GitHub orgs

https://github.com/heliumoss/hydrogen
https://github.com/Car-Thing-Hax-Community/ (we help support repositories under this repo and would also offer some machine usage for their projects.)

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not Sure

### What infrastructure (computing resources and network access) do you need?

We require continuous support to continue building up-to-date packages for the Spotify Car Thing. We would require networking, preferably decently fast to be able to distribute these packages to users. 

A decently beefy computer would be good to keep packages updated and perform builds of our operating system.

### Describe / Name the continuous integration (CI) system for this project.

Primarily GitHub Actions & Woodpecker CI

Will these machines be exclusively used for CI purposes?

Not exclusively, since we will also use it for builds of packages and our OS outside of CI for development.

Please share a public URL of the CI dashboard (if applicable).
Not currently available.

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes, we are okay with the use of Hydrogen and Helium logos on ARM's developer website.

### Please state your contributions to the open source community and any other relevant initiatives.

Helium LLC is migrating towards open sourcing all of our products, and we want to start this with the Spotify Car Thing / Hydrogen range of products. These projects are incredibly important to avoid mass e-waste after the death date of the Car Thing. We hope to provide this hardware with new life as a result.

## Important reminders and logistics

Thank you for your help >:3

**Comment by shipra-ps** [comment]
Closing the GitHub ticket for now, as discussed in the email.
